# -*- coding: utf-8 -*-
"""
Active Learning Pipeline for Force Field Development

Main orchestration script that calls:
    a) Training (model fitting)
    b) Sampling (candidate generation)
    c) Running DFT (placeholder for user to fill)
    d) Evaluating predictions

@author: n.patsalidis
"""
import sys
import os
import argparse
import numpy as np
import pandas as pd
from time import perf_counter

# Add path for local imports
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

import FF_Develop as ff
import qe_io


# =============================================================================
# Configuration Classes for Modular Input Files
# =============================================================================

class ConfigBase:
    """Base class for configuration file reading/writing."""
    
    defaults = {}
    
    @classmethod
    def _parse_value(cls, value_str):
        """Parse a string value to appropriate type."""
        value_str = value_str.strip()
        if value_str.isdigit():
            return int(value_str)
        try:
            return float(value_str)
        except ValueError:
            pass
        if value_str.lower() in ['true', 'yes', '1']:
            return True
        if value_str.lower() in ['false', 'no', '0']:
            return False
        return value_str
    
    @classmethod
    def from_file(cls, filepath):
        """Read configuration from file."""
        config = cls()
        print(filepath)
        if not os.path.exists(filepath):
            print(f"Warning: Config file {filepath} not found, using defaults")
            return config
        
        with open(filepath, 'r') as f:
            lines = f.readlines()
        
        for line in lines:
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            
            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                if key not in cls.defaults:
                    raise Exception(f"Unknown config option '{key}' in {filepath}. Valid options: {list(cls.defaults.keys())}")
                value = cls._parse_value(value)
                setattr(config, key, value)
                print(key, value)
            elif ':' in line:
                key, values_str = line.split(':', 1)
                key = key.strip()
                if key not in cls.defaults:
                    raise Exception(f"Unknown config option '{key}' in {filepath}. Valid options: {list(cls.defaults.keys())}")
                values = [cls._parse_value(v) for v in values_str.split()]
                setattr(config, key, values)
                print(key, values)
        return config
    
    def to_file(self, filepath):
        """Write configuration to file."""
        with open(filepath, 'w') as f:
            f.write(f'# {self.__class__.__name__} Configuration\n')
            f.write(f'# Generated by active_learning.py\n\n')
            
            for key, default in self.defaults.items():
                value = getattr(self, key, default)
                if isinstance(value, (list, tuple)):
                    f.write(f'{key} : {" ".join(str(v) for v in value)}\n')
                elif isinstance(value, bool):
                    f.write(f'{key} = {1 if value else 0}\n')
                else:
                    f.write(f'{key} = {value}\n')
    
    def to_dict(self):
        """Convert configuration to dictionary."""
        return {key: getattr(self, key) for key in self.defaults}


class ActiveLearningConfig(ConfigBase):
    """Configuration for active learning sampling parameters."""
    
    defaults = {
        'n_iterations': 20,
        'batch_size': 100,
        'sigma_init': 0.02,                   # initial sigma for perturbation/MC
        'target_temperature': 500.0,
        'sampling_method_schedule': 'auto',   # 'auto', 'perturbation', 'mc', 'md'
        'perturbation_iterations': 0,         # iterations 0 to this use perturbation
        'mc_iterations': 9,                   # iterations up to this use MC
        'fixed_types': [],
        'charge_map': '',
        'mass_map': '',
        # MC sampling parameters
        'max_mc_steps': 4000,                # maximum MC steps per system
        'max_candidates_per_system': 10000,   # maximum candidate configs per system
        'number_of_data_per_step': 100,      # data points to collect per step
        'translate_atoms': 0.2,               # probability to translate single atom
        'rotate_whole': 0.5,                  # probability to rotate whole choose_from set
        'translate_whole': 0.3,               # probability to translate whole choose_from set
        'mc_asymptotic_steps':0,              # number of mc steps to skip sampling
        # Data cleaning thresholds
        'max_energy_error': 150.0,              # kcal/mol - maximum estimated bfgs energy error (correlated to energy from local minima)
        'max_gradient_error': 1000.0,         # kcal/mol/Å - sanity check for extremely repulsive configs  
        'max_scf_correction': 0.5,            # kcal/mol/Å - maximum allowed SCF correction
        'forbidden_separation': 6.0,          # Å - cutoff for detecting disconnected clusters
        'max_ener' : 50,                      # maximum energy to keep the data in kcal/mol
        'max_force': 70.0,                    # maximum force magnitude to keep data in kcal/mol/Å
        # Langevin MD sampling parameters
        'md_initial_configs': 10,             # number of initial configs to start MD from
        'md_friction': 0.01,                  # friction coefficient (1/fs)
        'md_timestep': 1.0,                   # timestep in fs
        'md_integration_time': 1000.0,        # total integration time in fs
        'md_sampling_time': 10.0,             # store configurations every this many fs
        'md_save_traj': 'no',                 # 'no', 'sampled', 'full' - save trajectory to xyz
        'md_max_candidates': None,            # max candidates to sample; if None, run full integration_time
    }
    
    def __init__(self):
        for key, value in self.defaults.items():
            setattr(self, key, value)
    
    def get_sampling_method(self, iteration):
        """Determine sampling method based on iteration number."""
        if self.sampling_method_schedule != 'auto':
            return self.sampling_method_schedule
        
        if iteration < self.perturbation_iterations:
            return 'perturbation'
        elif iteration <= self.mc_iterations:
            return 'mc'
        else:
            return 'md'


class SchedulerConfig(ConfigBase):
    """Configuration for HPC scheduler settings."""
    
    defaults = {
        'scheduler': 'slurm',           # 'slurm', 'pbs', 'local'
        'partition': 'default',
        'nodes': 1,
        'ntasks_per_node': 4,
        'time_limit': '23:59:00',
        'job_name': 'AL_DFT',
        'memory': '8G',
        'account':'',
        'cpus-per-task':1,
        'modules': '',                  # space-separated module names
        'pre_commands': '',             # commands to run before DFT
        'post_commands': '',            # commands after DFT
        'wait_for_completion': True,
        'poll_interval': 6,            # seconds between job status checks
    }
    
    def __init__(self):
        for key, value in self.defaults.items():
            setattr(self, key, value)
            print(f'slurm:--> {key} : {value}')
    
    def generate_submit_script(self, work_dir, run_command):
        """Generate a scheduler submission script."""
        if self.scheduler == 'slurm':
            return self._generate_slurm_script(work_dir, run_command)
        elif self.scheduler == 'pbs':
            return self._generate_pbs_script(work_dir, run_command)
        else:
            return self._generate_local_script(work_dir, run_command)
    
    def _generate_slurm_script(self, work_dir, run_command):
        script = f"""#!/bin/bash
#SBATCH --job-name={self.job_name}
#SBATCH --output=slurm_%j.out
#SBATCH --error=slurm_%j.err
#SBATCH --nodes={self.nodes}
#SBATCH --ntasks-per-node={self.ntasks_per_node}
#SBATCH --partition={self.partition}
#SBATCH --time={self.time_limit}
#SBATCH --mem={self.memory}
"""
        if self.account !='':
            script +=f"#SBATCH --account={self.account}\n"
        if self.cpus-per-task !=1:
            script +=f"#SBATCH --cpus-per-task={self.cpus-per-task}\n"

        script += "\n cd {work_dir} \n "

        if self.modules:
            for mod in self.modules.split():
                script += f"module load {mod}\n"
            script += "\n"
        
        if self.pre_commands:
            script += f"{self.pre_commands}\n\n"
        
        script += f"{run_command}\n"
        
        if self.post_commands:
            script += f"\n{self.post_commands}\n"
        
        return script
    
    def _generate_pbs_script(self, work_dir, run_command):
        script = f"""#!/bin/bash
#PBS -N {self.job_name}
#PBS -o pbs_$PBS_JOBID.out
#PBS -e pbs_$PBS_JOBID.err
#PBS -l nodes={self.nodes}:ppn={self.ntasks_per_node}
#PBS -q {self.partition}
#PBS -l walltime={self.time_limit}
#PBS -l mem={self.memory}

cd {work_dir}

"""
        if self.modules:
            for mod in self.modules.split():
                script += f"module load {mod}\n"
            script += "\n"
        
        if self.pre_commands:
            script += f"{self.pre_commands}\n\n"
        
        script += f"{run_command}\n"
        
        if self.post_commands:
            script += f"\n{self.post_commands}\n"
        
        return script
    
    def _generate_local_script(self, work_dir, run_command):
        script = f"""#!/bin/bash
cd {work_dir}

"""
        if self.pre_commands:
            script += f"{self.pre_commands}\n\n"
        
        script += f"{run_command}\n"
        
        if self.post_commands:
            script += f"\n{self.post_commands}\n"
        
        return script


class DFTConfig(ConfigBase):
    """Configuration for DFT software settings."""
    
    defaults = {
        'software': 'qespresso',        # 'qespresso', 'gaussian', 'vasp'
        'executable': 'pw.x',
        'mpi_command': 'mpirun -np 4',
        'input_extension': '.in',
        'output_extension': '.log',
        # QE specific - input parameters
        'ecutwfc': 50.0,
        'ecutrho': 400.0,
        'input_dft': 'vdw-df3-opt1',
        'k_points': '1 1 1',
        'calculation': 'relax',
        'ibrav': 0,
        'conv_thr': 1e-7,
        'mixing_beta': 0.2,
        'electron_maxstep': 100,
        'scf_must_converge': '.false.',
        'nstep': 1,
        # Pseudopotential settings
        'pseudo_dir': './pseudo',
        'pseudo_map': '',               # e.g., "C:C.pbe.UPF,O:O.pbe.UPF"
    }
    
    def __init__(self):
        for key, value in self.defaults.items():
            setattr(self, key, value)
    
    def get_kpoints_tuple(self):
        """Parse k_points string to tuple."""
        return tuple(int(k) for k in self.k_points.split())
    
    def get_pseudo_map_dict(self):
        """Parse pseudo_map string to dictionary."""
        if not self.pseudo_map:
            return {}
        result = {}
        for pair in self.pseudo_map.split(','):
            if ':' in pair:
                elem, pseudo = pair.split(':')
                result[elem.strip()] = pseudo.strip()
        return result
    
    def get_run_command(self, input_file, output_file):
        """Generate the DFT run command."""
        if self.software in ['qespresso', 'qe']:
            return f"{self.mpi_command} {self.executable} < {input_file} > {output_file}"
        elif self.software == 'gaussian':
            return f"g16 < {input_file} > {output_file}"
        elif self.software == 'vasp':
            return f"{self.mpi_command} vasp_std"
        else:
            return f"{self.executable} {input_file} > {output_file}"


class ActiveLearningPipeline:
    """
    Orchestrates the active learning loop for force field development.
    
    Parameters
    ----------
    methodology_file : str
        Path to training.in (training parameters).
    potential_file : str
        Path to potential.in (model definitions).
    al_config : ActiveLearningConfig
        Active learning configuration.
    scheduler_config : SchedulerConfig
        Scheduler configuration.
    dft_config : DFTConfig
        DFT software configuration.
    datapath : str
        Path for data storage.
    results_path : str
        Path for results storage.
    """
    
    def __init__(self, methodology_file, potential_file, 
                 al_config=None, scheduler_config=None, dft_config=None,
                 datapath='data_al', results_path='Results_al'):
        
        # Store file paths
        self.methodology_file = methodology_file
        self.potential_file = potential_file
        self.datapath = datapath
        self.results_path = results_path
        
        # Load configurations (use defaults if not provided)
        
        self.al_config = al_config if al_config else ActiveLearningConfig()
        
        if not al_config:
            print('Warning: Default active learning methods are used')
        
        self.scheduler_config = scheduler_config if scheduler_config else SchedulerConfig()
        
        if not scheduler_config:
            print('Warning: Default scheduler_config methods are used')
        
        self.dft_config = dft_config if dft_config else DFTConfig()
        
        if not dft_config:
            print('Warning: Default dft_config methods are used')
        
        # Extract commonly used parameters
        self.n_iterations = self.al_config.n_iterations
        self.batch_size = self.al_config.batch_size
        self.existing_data = -1  # Set via command line -e flag. This is the default
        
        # Sampling parameters
        self.kB = 0.00198720375145233  # kcal/mol/K
        self.target_temperature = self.al_config.target_temperature
        self.beta_sampling = 1.0 / (self.kB * self.target_temperature)
        
        # DFT parameters - all accessed via self.dft_config
        self.pseudo_map = self.dft_config.get_pseudo_map_dict()
        
        # Initialize helpers
        self.al = ff.al_help()
        self.setup = ff.Setup_Interfacial_Optimization(methodology_file, potential_file)
        
        # Create directories
        os.makedirs(self.results_path, exist_ok=True)
        os.makedirs(self.datapath, exist_ok=True)
        
        return
        
    def run(self, start_iteration=0):
        """
        Run the active learning loop.
        
        Parameters
        ----------
        start_iteration : int
            Iteration to start from (for continuing runs).
        """
        print("=" * 60)
        print("ACTIVE LEARNING PIPELINE STARTED")
        print("=" * 60)
        
        for iteration in range(start_iteration, self.n_iterations + 1):
            print(f"\n{'='*60}")
            print(f"ITERATION {iteration}")
            print(f"{'='*60}")
            
            t_iter_start = perf_counter()
            
            # Read data
            data = self.read_data(iteration)
            
            # Clean data
            data = self.clean_data(data)
            
            # Step A: Training
            self.train(iteration, data)
            
            # Step B: Sampling (if not using existing data)
            
            if iteration >= self.existing_data:
            
                # Determine sampling method based on iteration
                sampling_method = self._get_sampling_method(iteration)
                print(f"Sampling method: {sampling_method}")
                
                selected_data = self.sample(iteration, data, sampling_method)
                
                # Step C: Prepare and run DFT (placeholder)
                self.prepare_dft(iteration, selected_data)
                
                self.prepare_submission_files(iteration)
                
                self.submit_and_wait(iteration)
                # Process DFT outputs
                self.process_dft_outputs(iteration)
            
            # Step D: Evaluation
            self.evaluate(iteration)
            
            print(f"\nIteration {iteration} completed in {perf_counter() - t_iter_start:.2f} sec")
            
            # Update input files for next iteration (from results folder)
            self.potential_file = f"{self.setup.runpath}/potential.in"
            self.setup = ff.Setup_Interfacial_Optimization(self.methodology_file, self.potential_file)
            
        print("\n" + "=" * 60)
        print("ACTIVE LEARNING PIPELINE COMPLETED")
        print("=" * 60)
    
    def _get_sampling_method(self, iteration):
        """Determine sampling method based on iteration number."""
        return self.al_config.get_sampling_method(iteration)
    
    def read_data(self, iteration):
        """
        Read data for the current iteration.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
            
        Returns
        -------
        data : pd.DataFrame
            Raw training data.
        """
        print("\n--- READING DATA ---")
        t0 = perf_counter()
        
        # Convert log files to ffdata format
        path_log = f'{self.datapath}/L{iteration}'
        path_ffdata = f'{self.datapath}/D{iteration}'
        self.al.log_to_ffdata(path_log, path_ffdata, dft_software=self.dft_config.software)
        
        # Accumulate all data up to current iteration
        data = pd.DataFrame()
        for n in range(iteration + 1):
            print(f'Reading iteration {n}')
            sys.stdout.flush()
            path_ffdata = f'{self.datapath}/D{n}'
            df = self.al.data_from_directory(path_ffdata)
            self.al.make_absolute_Energy_to_interaction(df, self.setup)
            data = pd.concat([data, df], ignore_index=True)
        
        self._print_column_stats(data['Energy'])
        
        print(f'Data reading time = {perf_counter() - t0:.3e} sec')
        return data
    
    
    def clean_data(self, data):
        """
        Clean the training data.
        
        Applies two types of cleaning:
        1. QE quality metrics filtering (energy_error, gradient_error, scf_correction)
        2. Standard FF cleaning (via al_help.clean_data)
        
        Parameters
        ----------
        data : pd.DataFrame
            Raw training data.
            
        Returns
        -------
        data : pd.DataFrame
            Cleaned training data.
        """
        print("\n--- CLEANING DATA ---")
        t0 = perf_counter()
        n_initial = len(data)
        
        # Step 1: Filter by QE quality metrics (if columns exist)
        if 'energy_error' in data.columns:
            n_before = len(data)
            mx = data["energy_error"].max()
            data = data[data['energy_error'] < self.al_config.max_energy_error]
            n_after = len(data)
            print(f'  Removed {n_before - n_after} configs with energy_error >= {self.al_config.max_energy_error}  |  max = {mx:4.3} ')
        
        if 'gradient_error' in data.columns:
            n_before = len(data)
            mx = data['gradient_error'].max()
            data = data[data['gradient_error'] < self.al_config.max_gradient_error]
            n_after = len(data)
            print(f'  Removed {n_before - n_after} configs with gradient_error >= {self.al_config.max_gradient_error}   |  mx = {mx:4.3}')
        
        if 'scf_correction' in data.columns:
            n_before = len(data)
            mx = data["scf_correction"].max()
            data = data[data['scf_correction'] < self.al_config.max_scf_correction]
            n_after = len(data)
            print(f'  Removed {n_before - n_after} configs with scf_correction >= {self.al_config.max_scf_correction}  |  mx = {mx:4.3}')
        
        n_after_qe = len(data)
        print(f'After QE quality filtering: {n_initial} -> {n_after_qe} configs')
        
        
        filt_clean = False
        for uns in np.unique(data['sys_name']):
            fsys = uns == data['sys_name']
            min_ener = data['Energy'][fsys].min()
            fhigh_ener = data['Energy'] > min_ener + self.al_config.max_ener
            fhigh_ener = np.logical_and(fsys, fhigh_ener)
            filt_clean = np.logical_or( filt_clean, fhigh_ener)
        
        data = data[ np.logical_not(filt_clean) ]
        n_ener_filt = len(data)
        print(f'After energy maximum threshold filtering: {n_after_qe} -> {n_ener_filt} configs')
        
        # Filter by maximum force magnitude
        if 'Forces' in data.columns and self.al_config.max_force is not None:
            max_force_per_config = data['Forces'].apply(lambda f: np.max(np.abs(f)) if f is not None else 0.0)
            max_f_val = max_force_per_config.max()
            filt_force = max_force_per_config <= self.al_config.max_force
            data = data[filt_force]
            n_force_filt = len(data)
            print(f'After max force filtering ({self.al_config.max_force} kcal/mol/Å): {n_ener_filt} -> {n_force_filt} configs  |  max = {max_f_val:.1f}')
        else:
            n_force_filt = n_ener_filt
        
        # Step 2: Clean well-separated structures (disconnected clusters)
        data = self.al.clean_well_separated_nanostructures(data, self.al_config.forbidden_separation)
        
        # Step 3: Standard FF cleaning
        data = self.al.clean_data(data, self.setup, self.beta_sampling)
        print('After FF cleaning:')
        self._print_column_stats(data['Energy'])
        
        print(f'Data cleaning time = {perf_counter() - t0:.3e} sec')
        return data
    
    def train(self, iteration, data):
        """
        Step A: Train the model on accumulated data.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        data : pd.DataFrame
            Cleaned training data.
        """
        print("\n--- STEP A: TRAINING ---")
        t0 = perf_counter()
        
        # Distribution plot
        ff.Data_Manager(data, self.setup).distribution('Energy')
        self.setup.run = iteration
        
        # Solve model
        t1 = perf_counter()
        data, optimizer = self.al.solve_model(data, self.setup)
        print(f'Training time = {perf_counter() - t1:.3e} sec')
        sys.stdout.flush()
        
        # store the current optimizer
        self.optimizer = optimizer

        # Write errors
        self.al.write_errors(optimizer.current_costs, iteration)
        
        print(f'Total training step time = {perf_counter() - t0:.3e} sec')
        return 

    def sample(self, iteration, data, sampling_method):
        """
        Step B: Sample candidate configurations.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        data : pd.DataFrame
            Current training data.
        sampling_method : str
            Sampling method ('perturbation', 'mc', 'md').
            
        Returns
        -------
        selected_data : pd.DataFrame
            Selected candidate configurations.
        """
        print("\n--- STEP B: SAMPLING ---")
        t0 = perf_counter()
        
        # Generate candidates based on method
        if sampling_method == 'perturbation':
            candidate_data = self.al.make_random_petrubations(data, sigma=self.sigma)
        elif sampling_method == 'md':
            candidate_data = self._sample_via_langevin(data, iteration)
        elif sampling_method == 'mc':
            candidate_data  = self.al.MC_sample( data, self.setup, self.al_config )
            
        else:
            raise NotImplementedError(f'Sampling method "{sampling_method}" is unknown')
        
        
        print(f'Candidate sampling time = {perf_counter() - t0:.3e} sec , number of candidate data = {len(candidate_data)}')
        
        # Select configurations
        t1 = perf_counter()
        if len(candidate_data) <= self.batch_size:
            selected_data = candidate_data
        else:
            selected_data = self.al.random_selection(
                data,  candidate_data, self.setup, self.al_config
            )
        selected_data = selected_data.reset_index(drop=True)
        
        print(f'Selection time = {perf_counter() - t1:.3e} sec')
        print(f'Selected {len(selected_data)} configurations')
        
        return selected_data
    
    def _sample_via_langevin(self, data, iteration):
        """Sample configurations using internal Langevin dynamics.
        
        Parameters
        ----------
        data : pd.DataFrame
            Current training data to start MD from.
        iteration : int
            Current iteration number for trajectory file naming.
        Returns
        -------
        candidate_data : pd.DataFrame
            Sampled configurations from MD trajectories.
        """
        # Parse mass map from config
        mass_map = self._parse_map_string(self.al_config.mass_map)
        
        # Add default masses for common elements if not specified
        default_masses = {
            'H': 1.008, 'C': 12.011, 'N': 14.007, 'O': 15.999,
            'S': 32.065, 'P': 30.974, 'F': 18.998, 'Cl': 35.453,
            'Br': 79.904, 'I': 126.90, 'Si': 28.086, 'B': 10.811,
            'Ag': 107.868, 'Au': 196.967, 'Cu': 63.546, 'Fe': 55.845,
            'Zn': 65.38, 'Pt': 195.084, 'Pd': 106.42, 'Ni': 58.693,
        }
        for elem, mass in default_masses.items():
            if elem not in mass_map:
                mass_map[elem] = mass
        
        # Create Langevin dynamics integrator with fixed atom types
        fixed_types = self.al_config.fixed_types
        langevin = LangevinDynamics(self.setup, self.al_config, mass_map, fixed_types)
        
        # Select initial configurations for MD
        n_init = min(self.al_config.md_initial_configs, len(data))
        init_data = data.sample(n=n_init).copy()
        
        # Ensure required columns exist
        required_cols = ['coords', 'at_type', 'natoms']
        for col in required_cols:
            if col not in init_data.columns:
                raise ValueError(f"Data missing required column: {col}")
        
        # Run Langevin dynamics with trajectory saving option
        save_traj = self.al_config.md_save_traj
        max_candidates = self.al_config.md_max_candidates
        sampled_df = langevin.integrate(
            init_data, n_configs=n_init, iteration=iteration,
            save_traj=save_traj, output_dir=self.setup.runpath,
            max_candidates=max_candidates
        )
        
        # Convert to format expected by rest of pipeline
        # Keep columns needed for DFT preparation plus Uclass
        candidate_data = sampled_df[['coords', 'at_type', 'natoms', 'lattice', 'sys_name', 'Uclass']].copy()
        
        return candidate_data
    
    def prepare_dft(self, iteration, selected_data):
        """
        Prepare DFT input files using qe_io.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        selected_data : pd.DataFrame
            Selected configurations for DFT. Must contain 'at_type', 'coords', and 'lattice' columns.
        """
        print("\n--- STEP C.1: PREPARING DFT INPUT FILES ---")
        
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        os.makedirs(dft_dir, exist_ok=True)
        
        dft_cfg = self.dft_config
        
        # Write input files for each configuration
        for idx, row in selected_data.iterrows():
            sys_name = row['sys_name']
            name = f'{sys_name}_{idx}'
            config_dir = f'{dft_dir}/{name}'
            os.makedirs(config_dir, exist_ok=True)
            
            at_types = row['at_type']
            coords = row['coords']
            
            if dft_cfg.software in ['qespresso', 'qe']:
                # Get cell from config - lattice must be preserved through sampling
                if 'lattice' not in row or row['lattice'] is None:
                    raise ValueError(f"Config {idx} missing 'lattice' column. Ensure lattice is preserved through sampling.")
                cell = row['lattice']
                
                # Create fixed filter from al_config.fixed_types
                fixed_types = self.al_config.fixed_types
                if fixed_types:
                    fixed = np.array( [True if at in fixed_types else False for  at in at_types ] )
                else:
                    fixed = None

                # Write QE input using all dft_config parameters
                qe_io.write_pw_input(
                    at_types=at_types,
                    positions=coords,
                    cell=cell,
                    pseudo_map=self.pseudo_map,
                    prefix=name,
                    path=config_dir,
                    input_dft=dft_cfg.input_dft,
                    fixed=fixed,
                    calculation=dft_cfg.calculation,
                    ibrav=dft_cfg.ibrav,
                    conv_thr=dft_cfg.conv_thr,
                    electron_maxstep=dft_cfg.electron_maxstep,
                    mixing_beta=dft_cfg.mixing_beta,
                    scf_must_converge=dft_cfg.scf_must_converge,
                    ecutwfc=dft_cfg.ecutwfc,
                    ecutrho=dft_cfg.ecutrho,
                    k_points=dft_cfg.get_kpoints_tuple(),
                    nstep=dft_cfg.nstep,
                    pseudo_dir = dft_cfg.pseudo_dir
                )
        
        # Write a summary file
        with open(f'{dft_dir}/batch_summary.txt', 'w') as f:
            f.write(f'Active Learning Iteration: {next_iter}\n')
            f.write(f'Number of configurations: {len(selected_data)}\n')
            f.write(f'Timestamp: {pd.Timestamp.now()}\n')
        
        print(f'Prepared {len(selected_data)} DFT input files in {dft_dir}')
    
    def prepare_submission_files(self, iteration):
        """
        Generate SLURM submission script and runlist for DFT calculations.
        
        Creates:
        - runlist.txt: List of DFT run commands for array job
        - run_dft.sh: SLURM submission script
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        print("\n--- STEP C.2: PREPARING DFT SUBMISSION ---")
        
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        sched = self.scheduler_config
        dft_cfg = self.dft_config
        
        # Get list of config directories
        config_dirs = [d for d in os.listdir(dft_dir) 
                       if os.path.isdir(f'{dft_dir}/{d}') and d != '__pycache__']
        config_dirs.sort()
        
        nbatch = len(config_dirs)
        if nbatch == 0:
            print(f"Warning: No configuration directories found in {dft_dir}")
            return
        
        # Write runlist.txt
        runlist_path = f'{dft_dir}/runlist.txt'
        with open(runlist_path, 'w') as f:
            for name in config_dirs:
                if dft_cfg.software in ['qespresso', 'qe']:
                    cmd = f"cd {name} ; mpirun -n {sched.ntasks_per_node} pw.x < {name}.in > {name}.log"
                elif dft_cfg.software == 'gaussian':
                    cmd = f"cd {name} ; g16 < {name}.com > {name}.log"
                else:
                    cmd = f"cd {name} ; echo 'Unknown DFT software'"
                f.write(f"{cmd}\n")
        
        print(f"Written runlist.txt with {nbatch} commands")
        
        # Generate SLURM script
        job_name = f"alR{next_iter}"
        script = f"""#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output=output
#SBATCH --error=error
#SBATCH --array=1-{nbatch}%{nbatch}
#SBATCH --nodes={sched.nodes}
#SBATCH --ntasks-per-node={sched.ntasks_per_node}
#SBATCH --partition={sched.partition}
#SBATCH --time={sched.time_limit}
#SBATCH --mem={sched.memory}

"""
        # Add module loads
        if sched.modules:
            for mod in sched.modules.split(','):
                mod = mod.strip()
                if mod:
                    script += f"module load {mod}\n"
            script += "\n"
        
        # Add pre-commands if any
        if sched.pre_commands:
            script += f"{sched.pre_commands}\n\n"
        
        # Add array job logic
        script += """# Get the command from runlist.txt based on array task ID
parent='.'
linecm=$(sed -n "${SLURM_ARRAY_TASK_ID}p" ${parent}/runlist.txt)

echo "${linecm}"
eval $linecm
"""
        
        # Add post-commands if any
        if sched.post_commands:
            script += f"\n{sched.post_commands}\n"
        
        # Write SLURM script
        script_path = f'{dft_dir}/run_dft.sh'
        with open(script_path, 'w') as f:
            f.write(script)
        
        print(f"Written SLURM script: {script_path}")
        print(f"Job name: {job_name}")
        print(f"Array: 1-{nbatch}%{nbatch}")
        print(f"\nTo submit: cd {dft_dir} && sbatch run_dft.sh")
        return 
    
    def submit_and_wait(self, iteration):
        """
        Submit SLURM job and wait for completion.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        import subprocess
        import time
        
        print("\n--- STEP C.3: SUBMITTING AND WAITING FOR DFT ---")
        
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        sched = self.scheduler_config
        
        # Submit the job
        result = subprocess.run(
            ['sbatch', 'run_dft.sh'],
            cwd=dft_dir,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print(f"Error submitting job: {result.stderr}")
            return
        
        # Extract job ID from output (e.g., "Submitted batch job 12345")
        try:
            job_id = result.stdout.strip().split()[-1]
            print(f"Submitted job {job_id}")
        except IndexError:
            print(f"Could not parse job ID from: {result.stdout}")
            return
        
        # Wait for job completion 
        print(f"Waiting for job {job_id} to complete (polling every {sched.poll_interval}s)...")
        
        checked_times = 0
        while True:
            # Check if job is still in queue
            check_result = subprocess.run(
                ['squeue', '-j', job_id, '-h'],
                capture_output=True,
                text=True
            )
            
            # If job is no longer in queue, it has finished
            if not check_result.stdout.strip():
                print(f"Job {job_id} completed")
                break
            
            # Show status
            status_info = check_result.stdout.strip().split()
            if len(status_info) >= 5 and checked_times%50==0:
                state = status_info[4]  # State is typically 5th column
                print(f"Job {job_id} status: {state}     |    {sched.poll_interval*checked_times} sec passed")
            
            time.sleep(sched.poll_interval)
            
            checked_times +=1
        
        print("DFT calculations finished")
        return
    
    def process_dft_outputs(self, iteration):
        """
        Copy validated DFT output files (.log/.out) from R{next_iter} to L{next_iter}.
        
        Only copies files that contain at least one valid configuration with
        energy, forces, and cell data.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        import shutil
        
        print("\n--- STEP C.4: PROCESSING DFT OUTPUTS ---")
        
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        output_dir = f'{self.datapath}/L{next_iter}'
        os.makedirs(output_dir, exist_ok=True)
        
        # Find and validate .log and .out files before copying
        copied_count = 0
        skipped_count = 0
        
        for root, dirs, files in os.walk(dft_dir):
            for f in files:
                if f.endswith('.out') or f.endswith('.log'):
                    src_path = os.path.join(root, f)
                    
                    # Validate the file has required data
                    if self._validate_qe_output(src_path):
                        dst_path = os.path.join(output_dir, f)
                        shutil.copy2(src_path, dst_path)
                        copied_count += 1
                    else:
                        print(f"Warning: {f} has not finished or missing data - not copied to L{next_iter}")
                        skipped_count += 1
        
        if copied_count == 0 and skipped_count == 0:
            print(f"No .log or .out files found in {dft_dir}")
        else:
            print(f"Copied {copied_count} valid output files to {output_dir}")
            if skipped_count > 0:
                print(f"Skipped {skipped_count} incomplete/invalid files")
    
    def _validate_qe_output(self, filepath):
        """
        Validate that a QE output file contains at least one complete configuration.
        
        Checks for presence of: energy, forces, and cell/lattice data.
        
        Returns
        -------
        bool
            True if file contains valid data, False otherwise.
        """
        try:
            with open(filepath, 'r') as f:
                lines = f.readlines()
            
            # Check for energy
            energies = qe_io.extract_energies(lines)
            if not energies.get('e_opt') and not energies.get('e_not_opt'):
                return False
            
            # Check for forces
            forces = qe_io.extract_forces(lines)
            if not forces or len(forces) == 0:
                return False
            
            # Check for cell/lattice
            cell = qe_io.extract_lattice_params(lines)
            if cell is None or (isinstance(cell, np.ndarray) and cell.size == 0):
                return False
            
            return True
            
        except Exception as e:
            print(f"Error validating {filepath}: {e}")
            return False
    
    def _read_qe_to_dataframe(self, filename):
        """
        Read QE output file and convert to DataFrame format.
        
        Parameters
        ----------
        filename : str
            Path to QE output file.
            
        Returns
        -------
        pd.DataFrame
            DataFrame with coords, at_type, Energy columns.
        """
        lines = qe_io.read_qe_output(filename)
        
        # Extract data
        at_types_list, coords_list = qe_io.extract_atomic_positions(lines)
        energies_dict = qe_io.extract_energies(lines)
        cells = qe_io.extract_lattice_params(lines)
        
        if not energies_dict['e_opt']:
            print(f"No converged energies in {filename}")
            return None
        
        # Match energies to configurations
        data_rows = []
        for i, (at_types, coords, energy) in enumerate(
            zip(at_types_list, coords_list, energies_dict['e_opt'])
        ):
            data_rows.append({
                'at_type': list(at_types),
                'coords': coords,
                'Energy': energy,
                'natoms': len(at_types),
                'readfile': filename
            })
        
        return pd.DataFrame(data_rows)
    
    def evaluate(self, iteration):
        """
        Step D: Evaluate model predictions on new data.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        print("\n--- STEP D: EVALUATION ---")
        t0 = perf_counter()
        
        next_iter = iteration + 1
        path_log = f'{self.datapath}/L{next_iter}'
        path_ffdata = f'{self.datapath}/D{next_iter}'
        
        # Check if data exists
        if not os.path.exists(path_log):
            print(f"No evaluation data found at {path_log}")
            return
        
        self.al.log_to_ffdata(path_log, path_ffdata, dft_software=self.dft_config.software)
        
        data = self.al.data_from_directory(path_ffdata)
        self.al.make_absolute_Energy_to_interaction(data, self.setup)

        predicted_costs = self.al.predict_model(data, self.setup)
        
        self.al.write_errors(predicted_costs, next_iter, 'predict')
        
        print(f'Evaluation time = {perf_counter() - t0:.3e} sec')
    
    def _default_cell(self, coords, padding=15.0):
        """Generate a default cubic cell based on coordinate extent."""
        coords = np.array(coords)
        extent = coords.max(axis=0) - coords.min(axis=0)
        size = max(extent) + padding
        return np.eye(3) * size
    
    def _parse_map_string(self, map_str):
        """Parse a map string like 'C:0.8,O:-0.4' to dict."""
        if not map_str:
            return {}
        result = {}
        for pair in map_str.split(','):
            if ':' in pair:
                key, val = pair.split(':')
                try:
                    result[key.strip()] = float(val.strip())
                except ValueError:
                    result[key.strip()] = val.strip()
        return result
    
    @staticmethod
    def _print_column_stats(column):
        """Print statistics for a DataFrame column."""
        print(f"  Column: {column.name}")
        print(f"  Max: {column.max():.4f}, Min: {column.min():.4f}")
        print(f"  Mean: {column.mean():.4f}, Std: {column.std():.4f}")


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Active Learning Pipeline for Force Field Development",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Input Files:
  The pipeline uses 5 separate input files for modular configuration:
  
  1. training.in  - Training/optimization parameters
  2. potential.in    - Force field model definitions (& sections)
  3. al.in - Sampling parameters and iteration settings
  4. scheduler.in    - HPC scheduler settings (SLURM/PBS)
  5. dft.in          - DFT software settings (QE/Gaussian)

Examples:
  # Using separate input files (recommended)
  python active_learning.py -m training.in -p potential.in -al al.in -sc scheduler.in -dft dft.in

  # Using legacy combined input file
  python active_learning.py -f combined.in

  # Generate template input files
  python active_learning.py --generate-templates
"""
    )
    
    # Input file arguments (modular mode)
    parser.add_argument('-m', '--methodology_file', type=str, default=None,
                        help='Methodology/training parameters file (training.in)')
    parser.add_argument('-p', '--potential_file', type=str, default=None,
                        help='Potential model definitions file (potential.in)')
    parser.add_argument('-al', '--al_config_file', type=str, default=None,
                        help='Active learning config file (al.in)')
    parser.add_argument('-sc', '--scheduler_file', type=str, default=None,
                        help='Scheduler config file (scheduler.in)')
    parser.add_argument('-dft', '--dft_file', type=str, default=None,
                        help='DFT settings file (dft.in)')
    
    # Path arguments
    parser.add_argument('-dp', '--datapath', type=str, default='data_al',
                        help='Main path for data storage')
    parser.add_argument('-rp', '--results_path', type=str, default='Results_al',
                        help='Path for results storage')
    
    # Override arguments (override config file values)
    parser.add_argument('--n_iterations', type=int, default=None,
                        help='Override: Number of active learning iterations')
    parser.add_argument('-b', '--batch_size', type=int, default=None,
                        help='Override: Batch size for configuration selection')
    parser.add_argument('-n', '--start_iteration', type=int, default=0,
                        help='Starting iteration (for continuing runs)')
    parser.add_argument('-e', '--existing_data', type=int, default=-1,
                        help='Last iteration with existing data (skip sampling up to this)')
    
    # Utility arguments
    parser.add_argument('--generate-templates', action='store_true',
                        help='Generate template input files and exit')
    
    return parser.parse_args()


def generate_template_files(output_dir='.'):
    """Generate template input files for all configurations."""
    os.makedirs(output_dir, exist_ok=True)
    
    # Active Learning config
    al_config = ActiveLearningConfig()
    al_config.to_file(os.path.join(output_dir, 'al.in'))
    
    # Scheduler config
    scheduler_config = SchedulerConfig()
    scheduler_config.to_file(os.path.join(output_dir, 'scheduler.in'))
    
    # DFT config
    dft_config = DFTConfig()
    dft_config.to_file(os.path.join(output_dir, 'dft.in'))
    
    # Methodology template
    methodology_template = """# Methodology/Training Parameters
# Generated template - modify as needed

representation  = AA
storing_path    = Results_al
run             = 0
runpath_attributes : run

max_ener        = 1.0
force_importance = 1.0
bC              = 50.0
bS              = 20.0

optimization_method = Adam
opt_disp        = 0
optimize        = 1
costf           = MSEo

training_method = fixed_lambda
random_initializations = 4
npareto         = 6
lambda_force    = 0.1

normalize_data  = 1

regularization_method = lasso
reg_par         = 0.00001

maxiter         = 130
max_moves       = 100
increased_stochasticity = 0.2
SLSQP_batchsize = 100000
tolerance       = 0.000001

train_perc      = 0.8
sampling_method = random
seed            = 1291412

polish          = 0
popsize         = 90
mutation        : 0.5 1.0
recombination   = 0.7

initial_temp    = 5230.0
restart_temp_ratio = 0.00002
local_search_scale = 1.0
accept          = -5.0
visit           = 2.62

learning_rate   = 0.0055
beta1           = 0.9
beta2           = 0.999
epsilon_adam    = 0.00000001
batch_size      = 50
decay_rate      = 0.015
weighting_method = Boltzman
w               = 1.0
bT              = 5.0

nLD             = 1
nPW             = 2
nBO             = 2
nAN             = 2
nDI             = 2

rho_r0          = 0.1
rho_rc          = 5.5

distance_map    = {('C', 'H'): (0.0, 1.2), ('N', 'H'): (0, 1.2)}
reference_energy = {'value': 0.0}
struct_types    = [('Ag',), ('C', 'H', 'N')]
rigid_types     = []
perturbation_method = atoms
lammps_potential_extra_lines = ['']
rigid_style     = single
extra_pair_coeff = {}
not_optimize_force_for = []
"""
    with open(os.path.join(output_dir, 'training.in'), 'w') as f:
        f.write(methodology_template)
    
    # Potential template
    potential_template = """# Potential Model Definitions
# Generated template - modify as needed
# Each model starts with &NAME and ends with /

&PW0 Ag C
FUNC LJ
sigma      : 3.0000000000000  1  0.20000  4.00000    0.00000
epsilon    : 0.5000000000000  1  0.00010  450.00000  0.00000
/

&PW0 Ag H
FUNC LJ
sigma      : 2.5000000000000  1  0.00100  4.00000    0.00000
epsilon    : 0.2000000000000  1  0.00000  450.00000  0.00000
/

&BO0 C H
FUNC MorseBond
re         : 1.1000000000000  1  1.00000  4.00000    0.00000
De         : 1.0000000000000  1  0.00000  450.00000  0.00000
alpha      : 2.0000000000000  1  0.00010  7.00000    0.00000
/

"""
    with open(os.path.join(output_dir, 'potential.in'), 'w') as f:
        f.write(potential_template)
    
    print(f"Generated template files in '{output_dir}':")
    print("  - training.in")
    print("  - potential.in")
    print("  - al.in")
    print("  - scheduler.in")
    print("  - dft.in")


class LangevinDynamics:
    """Langevin dynamics integrator using BAOAB scheme.
    
    Integrates equations of motion with stochastic thermostat for sampling
    configurations from the canonical ensemble.
    
    Parameters
    ----------
    setup : Setup_Interfacial_Optimization
        Setup object containing opt_models with trained parameters.
    al_config : ActiveLearningConfig
        Configuration containing MD parameters.
    mass_map : dict
        Mapping from atom type to mass in amu.
    fixed_types : list, optional
        List of atom types to freeze during integration.
    """
    
    # Conversion factors
    KB_KCAL = 0.001987204  # Boltzmann constant in kcal/(mol·K)
    # 1 kcal/mol = 0.0004184 amu·(Å/fs)² (for converting energy to mass*velocity²)
    # Equivalently: 1 amu·(Å/fs)² = 2390 kcal/mol
    KCAL_TO_AMU_A2_FS2 = 0.0004184
    
    def __init__(self, setup, al_config, mass_map, fixed_types=None):
        self.setup = setup
        self.al_config = al_config
        self.mass_map = mass_map
        self.fixed_types = fixed_types if fixed_types else []
        self.optimizer = None  # Created in integrate() with proper data
        
        # MD parameters
        self.dt = al_config.md_timestep  # fs
        self.friction = al_config.md_friction  # 1/fs
        self.temperature = al_config.target_temperature  # K
        self.integration_time = al_config.md_integration_time  # fs
        self.sampling_time = al_config.md_sampling_time  # fs
        
        # Precompute BAOAB coefficients
        gamma_dt = self.friction * self.dt
        self.c1 = np.exp(-gamma_dt)  # velocity decay factor
        self.c2 = np.sqrt(1.0 - self.c1**2)  # noise scaling
        
    def _get_masses(self, at_types):
        """Get mass array from atom types."""
        masses = np.array([self.mass_map.get(at, 1.0) for at in at_types])
        return masses
    
    def _get_mobile_mask(self, at_types):
        """Get boolean mask for mobile (non-frozen) atoms."""
        return np.array([at not in self.fixed_types for at in at_types])
    
    def _apply_pbc(self, coords, lattice):
        """Wrap coordinates into primary cell using PBC.
        
        NOTE: For molecular systems, per-atom wrapping breaks connectivity.
        This is disabled for now - forces are computed with MIC automatically.
        For interfacial systems, molecules should stay near the surface.
        """
        # Don't wrap individual atoms - this breaks molecules!
        # The force field handles MIC correctly in make_interactions.
        return coords
    
    def _compute_forces(self, which='opt', rebuild_topology=False):
        """Compute forces for all configurations in data.
        
        Parameters
        ----------
        rebuild_topology : bool
            If True, rebuild full topology (bonds, angles, etc.).
            If False, only recompute geometry from existing topology.
        """
        models = getattr(self.setup, which + '_models')
        params, bounds, fixed_params, isnot_fixed, reguls = self.optimizer.get_parameter_info(models)
        
        # Update descriptor info (geometry) - skip topology rebuild if not needed
        if rebuild_topology or 'interactions' not in self.optimizer.data.columns:
            ff.al_help.make_interactions(self.optimizer.data, self.setup)
        else:
            ff.al_help.update_descriptor_info(self.optimizer.data, self.setup)
        
        natoms_per_point = self.optimizer.data['natoms'].to_numpy()
        models_list_info = self.optimizer.get_list_of_model_information(models, 'all')
        
        Forces_tot = self.optimizer.computeForceClass(params, np.sum(natoms_per_point), models_list_info)
        
        # Split forces by configuration
        forces_dict = {}
        
        offset = 0
        for m, natoms in enumerate(natoms_per_point):
            forces_dict[m] = Forces_tot[offset:offset + natoms]
            offset += natoms
            
        return forces_dict
    
    def _compute_energies(self, which='opt'):
        """Compute classical energies for all configurations in data."""
        models = getattr(self.setup, which + '_models')
        params, bounds, fixed_params, isnot_fixed, reguls = self.optimizer.get_parameter_info(models)
        
        # Rebuild interactions with MIC (if not already done by _compute_forces)
        if 'descriptor_info' not in self.optimizer.data.columns:
            ff.al_help.make_interactions(self.optimizer.data, self.setup)
        
        ndata = len(self.optimizer.data)
        models_list_info = self.optimizer.get_list_of_model_information(models, 'all')
        
        Uclass = self.optimizer.computeUclass(params, ndata, models_list_info)
        
        # Return as dict keyed by index
        return {idx: Uclass[i] for i, idx in enumerate(self.optimizer.data.index)}
    
    def _write_xyz_frame(self, fh, coords, at_types, lattice=None, comment=''):
        """Write a single XYZ frame to file handle."""
        natoms = len(at_types)
        fh.write(f"{natoms}\n")
        if lattice is not None:
            lat_str = ' '.join([f"{x:.6f}" for row in lattice for x in row])
            fh.write(f"Lattice=\"{lat_str}\" {comment}\n")
        else:
            fh.write(f"{comment}\n")
        for at, xyz in zip(at_types, coords):
            fh.write(f"{at} {xyz[0]:.6f} {xyz[1]:.6f} {xyz[2]:.6f}\n")
    
    def integrate(self, init_data, n_configs=None, iteration=0, save_traj='no', output_dir='.', max_candidates=None):
        """Run Langevin dynamics and sample configurations.
        
        Parameters
        ----------
        init_data : pd.DataFrame
            Initial configurations with columns: coords, at_type, natoms, lattice (optional).
        n_configs : int, optional
            Number of configs to start from. If None, use all.
        iteration : int, optional
            Current iteration number for trajectory file naming.
        save_traj : str, optional
            'no' - don't save trajectories
            'sampled' - save only sampled frames
            'full' - save all frames
        output_dir : str, optional
            Directory to save trajectory files.
        max_candidates : int, optional
            Maximum number of candidates to sample. If reached, break early.
            If None, run full integration_time.
            
        Returns
        -------
        sampled_configs : pd.DataFrame
            Sampled configurations during integration.
        """
        import copy
        
        if n_configs is None:
            n_configs = len(init_data)
        else:
            n_configs = min(n_configs, len(init_data))
        
        # Select initial configurations
        data = init_data.iloc[:n_configs].copy()
        data = data.reset_index(drop=True)
        
        # Create FF_Optimizer with the selected data (needed for proper indexing)
        all_indexes = data.index.to_numpy()
        self.optimizer = ff.FF_Optimizer(data, all_indexes, all_indexes, self.setup)
        
        # Initialize velocities from Maxwell-Boltzmann (only for mobile atoms)
        velocities = {}
        mobile_masks = {}
        for idx in data.index:
            at_types = data.loc[idx, 'at_type']
            masses = self._get_masses(at_types)
            natoms = len(at_types)
            mobile_mask = self._get_mobile_mask(at_types)
            mobile_masks[idx] = mobile_mask
            
            # v = sqrt(kT/m) * random_normal, but zero for fixed atoms
            # sigma_v² = k_B*T * conversion / m, where conversion: kcal/mol -> amu·(Å/fs)²
            sigma_v = np.sqrt(self.KB_KCAL * self.temperature * self.KCAL_TO_AMU_A2_FS2 / masses)
            vel = np.random.randn(natoms, 3) * sigma_v[:, np.newaxis]
            vel[~mobile_mask] = 0.0  # Zero velocity for fixed atoms
            velocities[idx] = vel
            
        n_mobile = sum(mobile_masks[idx].sum() for idx in data.index)
        n_fixed = sum((~mobile_masks[idx]).sum() for idx in data.index)
        if n_fixed > 0:
            print(f"  Fixed atoms: {n_fixed}, Mobile atoms: {n_mobile}")
        
        # Storage for sampled configurations
        sampled_configs = []
        
        n_steps = int(self.integration_time / self.dt)
        sample_interval = max(1, int(self.sampling_time / self.dt))
        
        print(f"Running Langevin dynamics: {n_steps} steps, dt={self.dt} fs, T={self.temperature} K")
        print(f'{"-"*20}')
        print(f"Sampling every {sample_interval} steps ({self.sampling_time} fs)")
        print(f'{"-"*60}')
        
        # Reference to optimizer's data (same object, updated in place)
        data = self.optimizer.data
        
        # Setup trajectory file handles if saving
        traj_files = {}
        if save_traj != 'no':
            import os
            traj_dir = os.path.join(output_dir, f'iter{iteration}')
            os.makedirs(traj_dir, exist_ok=True)
            for idx in data.index:
                traj_path = os.path.join(traj_dir, f'traj_{save_traj}_{idx}.xyz')
                traj_files[idx] = open(traj_path, 'w')
            print(f"Saving {save_traj} trajectories to {traj_dir}")
        
        # Compute initial forces and energies
        forces = self._compute_forces()
        
        # Validate forces in first step using test_ForceClass (only on mobile atoms)
        # Get mobile atom indices from first config
        first_idx = data.index[0]
        mobile_atom_indices = np.where(mobile_masks[first_idx])[0].tolist()
        
        print(f"Validating analytical vs numerical forces on {len(mobile_atom_indices)} mobile atoms... mobile indices = {mobile_atom_indices}")
        print(f'{"-"*20}')
        _, max_diff = self.optimizer.test_ForceClass(which='opt', epsilon=1e-4, verbose=True, 
                                                      random_tries=3, order=4,
                                                      mobile_atoms=mobile_atom_indices)
        force_tol = 1e-2  # tolerance in kcal/(mol·Å)
        if max_diff > force_tol:
            raise RuntimeError(f"Force validation FAILED! max_diff={max_diff:.4e} > tol={force_tol:.4e}. "
                             f"Analytical forces do not match numerical gradients of U.")
        
        print(f'{"-"*60}')
        # Write initial frame (step 0) if saving trajectories
        if save_traj != 'no':
            energies = self._compute_energies()
            for idx in data.index:
                coords = np.array(self.optimizer.data.loc[idx, 'coords'], dtype=float)
                at_types = self.optimizer.data.loc[idx, 'at_type']
                lattice = self.optimizer.data.loc[idx, 'lattice'] if 'lattice' in self.optimizer.data.columns else None
                comment = f"step=0 time_fs=0.00 Uclass={energies[idx]:.4f} (initial)"
                self._write_xyz_frame(traj_files[idx], coords, at_types, lattice, comment)
        
        # Also store initial configuration in sampled_configs
        energies = self._compute_energies()
        for idx in data.index:
            coords = np.array(self.optimizer.data.loc[idx, 'coords'], dtype=float)
            at_types = self.optimizer.data.loc[idx, 'at_type']
            lattice = self.optimizer.data.loc[idx, 'lattice'] if 'lattice' in self.optimizer.data.columns else None
            sys_name = self.optimizer.data.loc[idx, 'sys_name'] if 'sys_name' in self.optimizer.data.columns else f'md_{idx}'
            sampled_configs.append({
                'coords': copy.deepcopy(coords),
                'at_type': at_types,
                'natoms': self.optimizer.data.loc[idx, 'natoms'],
                'lattice': lattice,
                'sys_name': sys_name,
                'step': 0,
                'time_fs': 0.0,
                'Uclass': energies[idx],
            })
        
        t_start = perf_counter()
        last_log_step = 0
        for step in range(n_steps):
            # BAOAB integrator
            for idx in data.index:
                coords = np.array(data.loc[idx, 'coords'], dtype=float)
                vel = velocities[idx].copy()
                force = forces[idx]
                at_types = data.loc[idx, 'at_type']
                masses = self._get_masses(at_types)
                lattice = data.loc[idx, 'lattice'] if 'lattice' in data.columns else None
                mobile = mobile_masks[idx]
                
                # Mass array for vectorized ops: a = F * conversion / m
                # F is in kcal/(mol·Å), convert to amu·Å/fs² then divide by mass
                m_inv = self.KCAL_TO_AMU_A2_FS2 / masses
                m_inv = m_inv[:, np.newaxis]
                
                # A: half kick (only mobile atoms)
                # Force field now returns physical force F = -dU/dr (fixed in ForcesPerModel)
                # Standard velocity update: v = v + F/m * dt
                vel[mobile] = vel[mobile] + 0.5 * self.dt * force[mobile] * m_inv[mobile]
                
                # B: half drift (only mobile atoms)
                coords[mobile] = coords[mobile] + 0.5 * self.dt * vel[mobile]
                
                # O: Ornstein-Uhlenbeck thermostat (only mobile atoms)
                sigma_v = np.sqrt(self.KB_KCAL * self.temperature * self.KCAL_TO_AMU_A2_FS2 / masses)
                noise = np.random.randn(len(masses), 3) * sigma_v[:, np.newaxis]
                vel[mobile] = self.c1 * vel[mobile] + self.c2 * noise[mobile]
                
                # B: half drift (only mobile atoms)
                coords[mobile] = coords[mobile] + 0.5 * self.dt * vel[mobile]
                
                # Apply PBC if lattice exists
                if lattice is not None:
                    coords = self._apply_pbc(coords, lattice)
                
                # Update data in optimizer
                self.optimizer.data.at[idx, 'coords'] = coords
                velocities[idx] = vel
            
            # Clear old descriptor_info (geometry) before recomputing forces
            # Keep 'interactions' (topology) - it doesn't change during MD
            if 'descriptor_info' in self.optimizer.data.columns:
                self.optimizer.data.drop(columns=['descriptor_info'], inplace=True, errors='ignore')
            
            # A: Compute new forces (after position update) - topology already cached
            forces = self._compute_forces()
            
            # Final half kick (only mobile atoms)
            for idx in data.index:
                vel = velocities[idx].copy()
                force = forces[idx]
                at_types = data.loc[idx, 'at_type']
                masses = self._get_masses(at_types)
                mobile = mobile_masks[idx]
                m_inv = self.KCAL_TO_AMU_A2_FS2 / masses
                m_inv = m_inv[:, np.newaxis]
                # Force field now returns physical force F = -dU/dr
                vel[mobile] = vel[mobile] + 0.5 * self.dt * force[mobile] * m_inv[mobile]
                velocities[idx] = vel
            
            # Write full trajectory if requested
            if save_traj == 'full':
                energies = self._compute_energies()
                for idx in data.index:
                    coords = np.array(self.optimizer.data.loc[idx, 'coords'], dtype=float)
                    at_types = self.optimizer.data.loc[idx, 'at_type']
                    lattice = self.optimizer.data.loc[idx, 'lattice'] if 'lattice' in self.optimizer.data.columns else None
                    comment = f"step={step+1} time_fs={(step+1)*self.dt:.2f} Uclass={energies[idx]:.4f}"
                    self._write_xyz_frame(traj_files[idx], coords, at_types, lattice, comment)
            
            # Sample configurations
            is_sample_step = (step + 1) % sample_interval == 0
            if is_sample_step:
                energies = self._compute_energies()
                for idx in data.index:
                    coords = np.array(self.optimizer.data.loc[idx, 'coords'], dtype=float)
                    at_types = self.optimizer.data.loc[idx, 'at_type']
                    lattice = self.optimizer.data.loc[idx, 'lattice'] if 'lattice' in self.optimizer.data.columns else None
                    sys_name = self.optimizer.data.loc[idx, 'sys_name'] if 'sys_name' in self.optimizer.data.columns else f'md_{idx}'
                    
                    sampled_configs.append({
                        'coords': copy.deepcopy(coords),
                        'at_type': at_types,
                        'natoms': self.optimizer.data.loc[idx, 'natoms'],
                        'lattice': lattice,
                        'sys_name': sys_name,
                        'step': step + 1,
                        'time_fs': (step + 1) * self.dt,
                        'Uclass': energies[idx],
                    })
                    
                    # Write sampled trajectory if requested
                    if save_traj == 'sampled':
                        comment = f"step={step+1} time_fs={(step+1)*self.dt:.2f} Uclass={energies[idx]:.4f}"
                        self._write_xyz_frame(traj_files[idx], coords, at_types, lattice, comment)
                
                # Check if max_candidates reached
                if max_candidates is not None and len(sampled_configs) >= max_candidates:
                    print(f"  Reached max_candidates={max_candidates} at step {step+1}. Breaking early.")
                    break
                    
            if (step + 1) % min(100, sample_interval) == 0:
                # Get max velocity and force for monitoring
                max_vel = max(np.abs(velocities[idx]).max() for idx in data.index)
                max_force = max(np.abs(forces[idx]).max() for idx in data.index)
                v_thermal = np.sqrt(self.KB_KCAL * self.temperature * self.KCAL_TO_AMU_A2_FS2 / 1.008)
                elapsed = perf_counter() - t_start
                steps_since_last = (step + 1) - last_log_step
                time_per_step = elapsed / (step + 1)
                last_log_step = step + 1
                print(f"  Step {step + 1}/{n_steps} | t={elapsed:.1f}s ({time_per_step*1000:.2f}ms/step) | v_max={max_vel:.4f} | F_max={max_force:.2f} | configs={len(sampled_configs)}")
                sys.stdout.flush()
        # Close trajectory files
        for fh in traj_files.values():
            fh.close()
        
        print(f"Langevin dynamics complete. Sampled {len(sampled_configs)} configurations.")
        return pd.DataFrame(sampled_configs)


def main():
    """Main entry point."""
    args = parse_arguments()
    
    # Handle template generation
    if args.generate_templates:
        generate_template_files('.')
        return
    
    # Determine mode: modular or legacy
    if args.methodology_file and args.potential_file:
        # Modular mode
        methodology_file = args.methodology_file
        potential_file = args.potential_file
    else:
        print("Error: Must provide: ")
        print("  - Both -m (training.in) and -p (potential.in) for modular mode")
        print("\nUse --generate-templates to create template input files.")
        return
    
    # Load configuration files
    al_config = ActiveLearningConfig()
    if args.al_config_file:
        al_config = ActiveLearningConfig.from_file(args.al_config_file)
    
    scheduler_config = SchedulerConfig()
    if args.scheduler_file:
        scheduler_config = SchedulerConfig.from_file(args.scheduler_file)
    
    dft_config = DFTConfig()
    if args.dft_file:
        dft_config = DFTConfig.from_file(args.dft_file)
    
    # Apply command-line overrides
    if args.n_iterations is not None:
        al_config.n_iterations = args.n_iterations
    if args.batch_size is not None:
        al_config.batch_size = args.batch_size
    
    # Create and run pipeline
    pipeline = ActiveLearningPipeline(
        methodology_file=methodology_file,
        potential_file=potential_file,
        al_config=al_config,
        scheduler_config=scheduler_config,
        dft_config=dft_config,
        datapath=args.datapath,
        results_path=args.results_path
    )
    # Override existing_data from command line if provided
    if args.existing_data != -1:
        pipeline.existing_data = args.existing_data
    
    print(f"start_iteration = {args.start_iteration}, existing_data = {pipeline.existing_data}")
    pipeline.run(start_iteration=args.start_iteration)


if __name__ == '__main__':
    main()
