# -*- coding: utf-8 -*-
"""
Active Learning Pipeline for Force Field Development

Main orchestration script that calls:
    a) Training (model fitting)
    b) Sampling (candidate generation)
    c) Running DFT (placeholder for user to fill)
    d) Evaluating predictions

@author: n.patsalidis
"""
import sys
import os
import argparse
import numpy as np
import pandas as pd
from time import perf_counter

# Add path for local imports
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

import FF_Develop as ff
import qe_io


# =============================================================================
# Configuration Classes for Modular Input Files
# =============================================================================

class ConfigBase:
    """Base class for configuration file reading/writing."""
    
    defaults = {}
    
    @classmethod
    def _parse_value(cls, value_str):
        """Parse a string value to appropriate type."""
        value_str = value_str.strip()
        if value_str.isdigit():
            return int(value_str)
        try:
            return float(value_str)
        except ValueError:
            pass
        if value_str.lower() in ['true', 'yes', '1']:
            return True
        if value_str.lower() in ['false', 'no', '0']:
            return False
        return value_str
    
    @classmethod
    def from_file(cls, filepath):
        """Read configuration from file."""
        config = cls()
        print(filepath)
        if not os.path.exists(filepath):
            print(f"Warning: Config file {filepath} not found, using defaults")
            return config
        
        with open(filepath, 'r') as f:
            lines = f.readlines()
        
        for line in lines:
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            
            if '=' in line:
                key, value = line.split('=', 1)
                key = key.strip()
                if key not in cls.defaults:
                    raise Exception(f"Unknown config option '{key}' in {filepath}. Valid options: {list(cls.defaults.keys())}")
                value = cls._parse_value(value)
                setattr(config, key, value)
                print(key, value)
            elif ':' in line:
                key, values_str = line.split(':', 1)
                key = key.strip()
                if key not in cls.defaults:
                    raise Exception(f"Unknown config option '{key}' in {filepath}. Valid options: {list(cls.defaults.keys())}")
                values = [cls._parse_value(v) for v in values_str.split()]
                setattr(config, key, values)
                print(key, values)
        return config
    
    def to_file(self, filepath):
        """Write configuration to file."""
        with open(filepath, 'w') as f:
            f.write(f'# {self.__class__.__name__} Configuration\n')
            f.write(f'# Generated by active_learning.py\n\n')
            
            for key, default in self.defaults.items():
                value = getattr(self, key, default)
                if isinstance(value, (list, tuple)):
                    f.write(f'{key} : {" ".join(str(v) for v in value)}\n')
                elif isinstance(value, bool):
                    f.write(f'{key} = {1 if value else 0}\n')
                else:
                    f.write(f'{key} = {value}\n')
    
    def to_dict(self):
        """Convert configuration to dictionary."""
        return {key: getattr(self, key) for key in self.defaults}


class ActiveLearningConfig(ConfigBase):
    """Configuration for active learning sampling parameters."""
    
    defaults = {
        'n_iterations': 20,
        'batch_size': 100,
        'sigma_init': 0.02,                   # initial sigma for perturbation/MC
        'start_iteration': 0,
        'existing_data': -1,
        'target_temperature': 500.0,
        'sampling_method_schedule': 'auto',   # 'auto', 'perturbation', 'mc', 'md'
        'perturbation_iterations': 0,         # iterations 0 to this use perturbation
        'mc_iterations': 9,                   # iterations up to this use MC
        'fixed_types': [],
        'charge_map': '',
        'mass_map': '',
        # MC sampling parameters
        'max_mc_steps': 4000,                # maximum MC steps per system
        'max_candidates_per_system': 10000,   # maximum candidate configs per system
        'number_of_data_per_step': 100,      # data points to collect per step
        'translate_atoms': 0.2,               # probability to translate single atom
        'rotate_whole': 0.5,                  # probability to rotate whole choose_from set
        'translate_whole': 0.3,               # probability to translate whole choose_from set
    }
    
    def __init__(self):
        for key, value in self.defaults.items():
            setattr(self, key, value)
    
    def get_sampling_method(self, iteration):
        """Determine sampling method based on iteration number."""
        if self.sampling_method_schedule != 'auto':
            return self.sampling_method_schedule
        
        if iteration < self.perturbation_iterations:
            return 'perturbation'
        elif iteration <= self.mc_iterations:
            return 'mc'
        else:
            return 'md'


class SchedulerConfig(ConfigBase):
    """Configuration for HPC scheduler settings."""
    
    defaults = {
        'scheduler': 'slurm',           # 'slurm', 'pbs', 'local'
        'partition': 'default',
        'nodes': 1,
        'ntasks_per_node': 4,
        'time_limit': '23:59:00',
        'job_name': 'AL_DFT',
        'memory': '8G',
        'modules': '',                  # space-separated module names
        'pre_commands': '',             # commands to run before DFT
        'post_commands': '',            # commands after DFT
        'wait_for_completion': True,
        'poll_interval': 60,            # seconds between job status checks
    }
    
    def __init__(self):
        for key, value in self.defaults.items():
            setattr(self, key, value)
    
    def generate_submit_script(self, work_dir, run_command):
        """Generate a scheduler submission script."""
        if self.scheduler == 'slurm':
            return self._generate_slurm_script(work_dir, run_command)
        elif self.scheduler == 'pbs':
            return self._generate_pbs_script(work_dir, run_command)
        else:
            return self._generate_local_script(work_dir, run_command)
    
    def _generate_slurm_script(self, work_dir, run_command):
        script = f"""#!/bin/bash
#SBATCH --job-name={self.job_name}
#SBATCH --output=slurm_%j.out
#SBATCH --error=slurm_%j.err
#SBATCH --nodes={self.nodes}
#SBATCH --ntasks-per-node={self.ntasks_per_node}
#SBATCH --partition={self.partition}
#SBATCH --time={self.time_limit}
#SBATCH --mem={self.memory}

cd {work_dir}

"""
        if self.modules:
            for mod in self.modules.split():
                script += f"module load {mod}\n"
            script += "\n"
        
        if self.pre_commands:
            script += f"{self.pre_commands}\n\n"
        
        script += f"{run_command}\n"
        
        if self.post_commands:
            script += f"\n{self.post_commands}\n"
        
        return script
    
    def _generate_pbs_script(self, work_dir, run_command):
        script = f"""#!/bin/bash
#PBS -N {self.job_name}
#PBS -o pbs_$PBS_JOBID.out
#PBS -e pbs_$PBS_JOBID.err
#PBS -l nodes={self.nodes}:ppn={self.ntasks_per_node}
#PBS -q {self.partition}
#PBS -l walltime={self.time_limit}
#PBS -l mem={self.memory}

cd {work_dir}

"""
        if self.modules:
            for mod in self.modules.split():
                script += f"module load {mod}\n"
            script += "\n"
        
        if self.pre_commands:
            script += f"{self.pre_commands}\n\n"
        
        script += f"{run_command}\n"
        
        if self.post_commands:
            script += f"\n{self.post_commands}\n"
        
        return script
    
    def _generate_local_script(self, work_dir, run_command):
        script = f"""#!/bin/bash
cd {work_dir}

"""
        if self.pre_commands:
            script += f"{self.pre_commands}\n\n"
        
        script += f"{run_command}\n"
        
        if self.post_commands:
            script += f"\n{self.post_commands}\n"
        
        return script


class DFTConfig(ConfigBase):
    """Configuration for DFT software settings."""
    
    defaults = {
        'software': 'qespresso',        # 'qespresso', 'gaussian', 'vasp'
        'executable': 'pw.x',
        'mpi_command': 'mpirun -np 4',
        'input_extension': '.in',
        'output_extension': '.log',
        # QE specific
        'ecutwfc': 80.0,
        'ecutrho': 320.0,
        'input_dft': 'vdw-df2',
        'k_points': '1 1 1',
        'calculation': 'scf',
        'conv_thr': 1e-6,
        'mixing_beta': 0.7,
        'electron_maxstep': 100,
        # Pseudopotential directory
        'pseudo_dir': './pseudo',
        'pseudo_map': '',               # e.g., "C:C.pbe.UPF,O:O.pbe.UPF"
        # QE output quality thresholds for data cleaning
        'max_energy_error': 0.1,        # kcal/mol - maximum allowed energy error
        'max_gradient_error': 1.0,      # kcal/mol/Å - maximum allowed gradient error  
        'max_scf_correction': 0.5,      # kcal/mol/Å - maximum allowed SCF correction
    }
    
    def __init__(self):
        for key, value in self.defaults.items():
            setattr(self, key, value)
    
    def get_kpoints_tuple(self):
        """Parse k_points string to tuple."""
        return tuple(int(k) for k in self.k_points.split())
    
    def get_pseudo_map_dict(self):
        """Parse pseudo_map string to dictionary."""
        if not self.pseudo_map:
            return {}
        result = {}
        for pair in self.pseudo_map.split(','):
            if ':' in pair:
                elem, pseudo = pair.split(':')
                result[elem.strip()] = pseudo.strip()
        return result
    
    def get_run_command(self, input_file, output_file):
        """Generate the DFT run command."""
        if self.software in ['qespresso', 'qe']:
            return f"{self.mpi_command} {self.executable} < {input_file} > {output_file}"
        elif self.software == 'gaussian':
            return f"g16 < {input_file} > {output_file}"
        elif self.software == 'vasp':
            return f"{self.mpi_command} vasp_std"
        else:
            return f"{self.executable} {input_file} > {output_file}"


class ActiveLearningPipeline:
    """
    Orchestrates the active learning loop for force field development.
    
    Parameters
    ----------
    methodology_file : str
        Path to training.in (training parameters).
    potential_file : str
        Path to potential.in (model definitions).
    al_config : ActiveLearningConfig
        Active learning configuration.
    scheduler_config : SchedulerConfig
        Scheduler configuration.
    dft_config : DFTConfig
        DFT software configuration.
    datapath : str
        Path for data storage.
    results_path : str
        Path for results storage.
    """
    
    def __init__(self, methodology_file, potential_file, 
                 al_config=None, scheduler_config=None, dft_config=None,
                 datapath='data_al', results_path='Results_al'):
        
        # Store file paths
        self.methodology_file = methodology_file
        self.potential_file = potential_file
        self.datapath = datapath
        self.results_path = results_path
        
        # Load configurations (use defaults if not provided)
        
        self.al_config = al_config if al_config else ActiveLearningConfig()
        
        if not al_config:
            print('Warning: Default active learning methods are used')
        
        self.scheduler_config = scheduler_config if scheduler_config else SchedulerConfig()
        
        if not scheduler_config:
            print('Warning: Default scheduler_config methods are used')
        
        self.dft_config = dft_config if dft_config else DFTConfig()
        
        if not dft_config:
            print('Warning: Default dft_config methods are used')
        
        # Extract commonly used parameters
        self.n_iterations = self.al_config.n_iterations
        self.batch_size = self.al_config.batch_size
        self.sigma = self.al_config.sigma
        self.existing_data = self.al_config.existing_data
        
        # Sampling parameters
        self.kB = 0.00198720375145233  # kcal/mol/K
        self.target_temperature = self.al_config.target_temperature
        self.beta_sampling = 1.0 / (self.kB * self.target_temperature)
        
        # DFT parameters
        self.dft_software = self.dft_config.software
        self.pseudo_map = self.dft_config.get_pseudo_map_dict()
        
        # QE config dict for backward compatibility with prepare_dft
        self.qe_config = {
            'calculation': self.dft_config.calculation,
            'k_points': self.dft_config.get_kpoints_tuple(),
            'ecutwfc': self.dft_config.ecutwfc,
            'ecutrho': self.dft_config.ecutrho,
            'input_dft': self.dft_config.input_dft,
        }
        
        # Initialize helpers
        self.al = ff.al_help()
        self.setup = ff.Setup_Interfacial_Optimization(methodology_file, potential_file)
        
        # Create directories
        os.makedirs(self.results_path, exist_ok=True)
        os.makedirs(self.datapath, exist_ok=True)
        
        return
        
    def run(self, start_iteration=0):
        """
        Run the active learning loop.
        
        Parameters
        ----------
        start_iteration : int
            Iteration to start from (for continuing runs).
        """
        print("=" * 60)
        print("ACTIVE LEARNING PIPELINE STARTED")
        print("=" * 60)
        
        for iteration in range(start_iteration, self.n_iterations + 1):
            print(f"\n{'='*60}")
            print(f"ITERATION {iteration}")
            print(f"{'='*60}")
            
            t_iter_start = perf_counter()
            
            # Read data
            data = self.read_data(iteration)
            
            # Clean data
            data = self.clean_data(data)
            
            # Step A: Training
            self.train(iteration, data)
            
            # Step B: Sampling (if not using existing data)
            if iteration >= self.existing_data:
            
                # Determine sampling method based on iteration
                sampling_method = self._get_sampling_method(iteration)
                print(f"Sampling method: {sampling_method}")
                
                selected_data = self.sample(iteration, data, sampling_method)
                
                # Step C: Prepare and run DFT (placeholder)
                self.prepare_dft(iteration, selected_data)
                self.run_dft(iteration)
                
                # Process DFT outputs
                self.process_dft_outputs(iteration)
            
            # Step D: Evaluation
            self.evaluate(iteration)
            
            print(f"\nIteration {iteration} completed in {perf_counter() - t_iter_start:.2f} sec")
            
            # Update input files for next iteration (from results folder)
            self.methodology_file = f"{self.setup.runpath}/training.in"
            self.potential_file = f"{self.setup.runpath}/potential.in"
            self.setup = ff.Setup_Interfacial_Optimization(self.methodology_file, self.potential_file)
            
        print("\n" + "=" * 60)
        print("ACTIVE LEARNING PIPELINE COMPLETED")
        print("=" * 60)
    
    def _get_sampling_method(self, iteration):
        """Determine sampling method based on iteration number."""
        return self.al_config.get_sampling_method(iteration)
    
    def read_data(self, iteration):
        """
        Read data for the current iteration.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
            
        Returns
        -------
        data : pd.DataFrame
            Raw training data.
        """
        print("\n--- READING DATA ---")
        t0 = perf_counter()
        
        # Convert log files to ffdata format
        path_log = f'{self.datapath}/L{iteration}'
        path_ffdata = f'{self.datapath}/D{iteration}'
        self.al.log_to_ffdata(path_log, path_ffdata, dft_software=self.dft_software)
        
        # Accumulate all data up to current iteration
        data = pd.DataFrame()
        for n in range(iteration + 1):
            print(f'Reading iteration {n}')
            sys.stdout.flush()
            path_ffdata = f'{self.datapath}/D{n}'
            df = self.al.data_from_directory(path_ffdata)
            self.al.make_absolute_Energy_to_interaction(df, self.setup)
            data = pd.concat([data, df], ignore_index=True)
        
        self._print_column_stats(data['Energy'])
        
        print(f'Data reading time = {perf_counter() - t0:.3e} sec')
        return data
    
    def clean_data(self, data):
        """
        Clean the training data.
        
        Applies two types of cleaning:
        1. QE quality metrics filtering (energy_error, gradient_error, scf_correction)
        2. Standard FF cleaning (via al_help.clean_data)
        
        Parameters
        ----------
        data : pd.DataFrame
            Raw training data.
            
        Returns
        -------
        data : pd.DataFrame
            Cleaned training data.
        """
        print("\n--- CLEANING DATA ---")
        t0 = perf_counter()
        n_initial = len(data)
        
        # Step 1: Filter by QE quality metrics (if columns exist)
        if 'energy_error' in data.columns:
            n_before = len(data)
            data = data[data['energy_error'] < self.dft_config.max_energy_error]
            n_after = len(data)
            print(f'  Removed {n_before - n_after} configs with energy_error >= {self.dft_config.max_energy_error}  |  max = {data["energy_error"].max():4.3} ')
        
        if 'gradient_error' in data.columns:
            n_before = len(data)
            data = data[data['gradient_error'] < self.dft_config.max_gradient_error]
            n_after = len(data)
            print(f'  Removed {n_before - n_after} configs with gradient_error >= {self.dft_config.max_gradient_error}   |  max = {data["gradient_error"].max():4.3}')
        
        if 'scf_correction' in data.columns:
            n_before = len(data)
            data = data[data['scf_correction'] < self.dft_config.max_scf_correction]
            n_after = len(data)
            print(f'  Removed {n_before - n_after} configs with scf_correction >= {self.dft_config.max_scf_correction}  |  max = {data["scf_correction"].max():4.3}')
        
        n_after_qe = len(data)
        print(f'After QE quality filtering: {n_initial} -> {n_after_qe} configs')
        
        # Step 2: Standard FF cleaning
        data = self.al.clean_data(data, self.setup, self.beta_sampling)
        print('After FF cleaning:')
        self._print_column_stats(data['Energy'])
        
        print(f'Data cleaning time = {perf_counter() - t0:.3e} sec')
        return data
    
    def train(self, iteration, data):
        """
        Step A: Train the model on accumulated data.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        data : pd.DataFrame
            Cleaned training data.
        """
        print("\n--- STEP A: TRAINING ---")
        t0 = perf_counter()
        
        # Distribution plot
        ff.Data_Manager(data, self.setup).distribution('Energy')
        self.setup.run = iteration
        
        # Solve model
        t1 = perf_counter()
        data, optimizer = self.al.solve_model(data, self.setup)
        print(f'Training time = {perf_counter() - t1:.3e} sec')
        sys.stdout.flush()
        
        # Write errors
        self.al.write_errors(optimizer.current_costs, iteration)
        
        print(f'Total training step time = {perf_counter() - t0:.3e} sec')
        return 

    def sample(self, iteration, data, sampling_method):
        """
        Step B: Sample candidate configurations.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        data : pd.DataFrame
            Current training data.
        sampling_method : str
            Sampling method ('perturbation', 'mc', 'md').
            
        Returns
        -------
        selected_data : pd.DataFrame
            Selected candidate configurations.
        """
        print("\n--- STEP B: SAMPLING ---")
        t0 = perf_counter()
        
        # Create args namespace for sampling functions
        class SamplingArgs:
            pass
        
        args = SamplingArgs()
        args.num = iteration
        args.sigma = self.sigma
        #args.charge_map = self._parse_map_string(self.config.get('charge_map_str', ''))
        #args.mass_map = self._parse_map_string(self.config.get('mass_map_str', ''))
        #args.writing_path = 'lammps_working'
        
        # Generate candidates based on method
        if sampling_method == 'perturbation':
            candidate_data = self.al.make_random_petrubations(data, sigma=self.sigma)
        elif sampling_method == 'md':
            candidate_data, self.beta_sampling = self.al.sample_via_lammps(
                data, self.setup, args, self.beta_sampling
            )
        elif sampling_method == 'mc':
            candidate_data, self.beta_sampling = self.al.MC_sample(
                data, self.setup, al_config )
            
        else:
            raise NotImplementedError(f'Sampling method "{sampling_method}" is unknown')
        
        
        print(f'Candidate sampling time = {perf_counter() - t0:.3e} sec , number of candidate data = {len(candidate_data)}')
        
        # Select configurations
        t1 = perf_counter()
        if len(candidate_data) <= self.batch_size:
            selected_data = candidate_data
        else:
            selected_data = self.al.random_selection(
                data, self.setup, candidate_data, self.batch_size
            )
        selected_data = selected_data.reset_index(drop=True)
        
        print(f'Selection time = {perf_counter() - t1:.3e} sec')
        print(f'Selected {len(selected_data)} configurations')
        
        return selected_data
    
    def prepare_dft(self, iteration, selected_data, dft_software='QE'):
        """
        Prepare DFT input files using qe_io.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        selected_data : pd.DataFrame
            Selected configurations for DFT.
        """
        print("\n--- STEP C.1: PREPARING DFT INPUT FILES ---")
        
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        os.makedirs(dft_dir, exist_ok=True)
        
        # Write QE input files for each configuration
        for idx, row in selected_data.iterrows():
            config_dir = f'{dft_dir}/config_{idx}'
            os.makedirs(config_dir, exist_ok=True)
            
            at_types = row['at_type']
            coords = row['coords']
            if dft_software == 'QE':
                # Get cell from config or use default
                cell = row.get('lattice', self._default_cell(coords))
                # Write QE input
                qe_io.write_pw_input(
                    at_types=at_types,
                    positions=coords,
                    cell=cell,
                    pseudo_map=self.pseudo_map,
                    prefix=f'config_{idx}',
                    path=config_dir,
                    calculation=self.qe_config.get('calculation', 'scf'),
                    k_points=self.qe_config.get('k_points', (1, 1, 1)),
                    ecutwfc=self.qe_config.get('ecutwfc', 80),
                    ecutrho=self.qe_config.get('ecutrho', 320),
                    input_dft=self.qe_config.get('input_dft', 'vdw-df2'),
                )

                if False:
                    # Also write xyz for reference
                    qe_io.write_xyz(
                        f'{config_dir}/structure.xyz',
                        at_types,
                        coords,
                        comment=f'Config {idx} for DFT'
                    )
        if True:
            # Write a summary file
            with open(f'{dft_dir}/batch_summary.txt', 'w') as f:
                f.write(f'Active Learning Iteration: {next_iter}\n')
                f.write(f'Number of configurations: {len(selected_data)}\n')
                f.write(f'Timestamp: {pd.Timestamp.now()}\n')
        
        print(f'Prepared {len(selected_data)} DFT input files in {dft_dir}')
    
    def run_dft(self, iteration):
        """
        Run DFT calculations.
        
        **PLACEHOLDER**: User should fill this method with their HPC scheduler calls.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        print("\n--- STEP C.2: RUNNING DFT ---")
        print("=" * 40)
        print("PLACEHOLDER: DFT EXECUTION")
        print("=" * 40)
        print("""
        TODO: Fill this method with your DFT execution logic:
        
        1. Submit jobs to your HPC scheduler (SLURM, PBS, etc.)
        2. Wait for jobs to complete
        3. Check for convergence/errors
        
        Example for SLURM:
        -----------------
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        
        # Submit job
        result = subprocess.run(
            ['sbatch', 'run_qe.sh'],
            cwd=dft_dir,
            capture_output=True,
            text=True
        )
        job_id = result.stdout.split()[-1]
        
        # Wait for completion
        while True:
            result = subprocess.run(
                ['squeue', '-j', job_id],
                capture_output=True,
                text=True
            )
            if job_id not in result.stdout:
                break
            time.sleep(60)
        """)
        print("=" * 40)
        print("Skipping DFT execution - user must implement")
        print("=" * 40)
    
    def process_dft_outputs(self, iteration):
        """
        Process DFT output files and convert to training data format.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        print("\n--- STEP C.3: PROCESSING DFT OUTPUTS ---")
        
        next_iter = iteration + 1
        dft_dir = f'{self.datapath}/R{next_iter}'
        output_dir = f'{self.datapath}/L{next_iter}'
        os.makedirs(output_dir, exist_ok=True)
        
        # Find all QE output files
        qe_outputs = []
        for root, dirs, files in os.walk(dft_dir):
            for f in files:
                if f.endswith('.out') or f.endswith('.log'):
                    qe_outputs.append(os.path.join(root, f))
        
        if not qe_outputs:
            print(f"No QE output files found in {dft_dir}")
            print("Looking for *.out or *.log files")
            return
        
        # Process each output file
        all_data = []
        for qe_file in qe_outputs:
            try:
                data = self._read_qe_to_dataframe(qe_file)
                if data is not None:
                    all_data.append(data)
            except Exception as e:
                print(f"Error processing {qe_file}: {e}")
        
        if all_data:
            combined_data = pd.concat(all_data, ignore_index=True)
            # Save in format expected by al_help
            combined_data.to_pickle(f'{output_dir}/dft_data.pkl')
            print(f'Processed {len(combined_data)} configurations from DFT')
        else:
            print("No valid DFT data extracted")
    
    def _read_qe_to_dataframe(self, filename):
        """
        Read QE output file and convert to DataFrame format.
        
        Parameters
        ----------
        filename : str
            Path to QE output file.
            
        Returns
        -------
        pd.DataFrame
            DataFrame with coords, at_type, Energy columns.
        """
        lines = qe_io.read_qe_output(filename)
        
        # Extract data
        at_types_list, coords_list = qe_io.extract_atomic_positions(lines)
        energies_dict = qe_io.extract_energies(lines)
        cells = qe_io.extract_lattice_params(lines)
        
        if not energies_dict['e_opt']:
            print(f"No converged energies in {filename}")
            return None
        
        # Match energies to configurations
        data_rows = []
        for i, (at_types, coords, energy) in enumerate(
            zip(at_types_list, coords_list, energies_dict['e_opt'])
        ):
            data_rows.append({
                'at_type': list(at_types),
                'coords': coords,
                'Energy': energy,
                'natoms': len(at_types),
                'readfile': filename
            })
        
        return pd.DataFrame(data_rows)
    
    def evaluate(self, iteration):
        """
        Step D: Evaluate model predictions on new data.
        
        Parameters
        ----------
        iteration : int
            Current iteration number.
        """
        print("\n--- STEP D: EVALUATION ---")
        t0 = perf_counter()
        
        next_iter = iteration + 1
        path_log = f'{self.datapath}/L{next_iter}'
        path_ffdata = f'{self.datapath}/D{next_iter}'
        
        # Check if data exists
        if not os.path.exists(path_log):
            print(f"No evaluation data found at {path_log}")
            return
        
        self.al.log_to_ffdata(path_log, path_ffdata, dft_software=self.dft_software)
        
        data = self.al.data_from_directory(path_ffdata)
        self.al.make_absolute_Energy_to_interaction(data, self.setup)

        predicted_costs = self.al.predict_model(data, self.setup)
        
        self.al.write_errors(predicted_costs, next_iter, 'predict')
        
        print(f'Evaluation time = {perf_counter() - t0:.3e} sec')
    
    def _default_cell(self, coords, padding=15.0):
        """Generate a default cubic cell based on coordinate extent."""
        coords = np.array(coords)
        extent = coords.max(axis=0) - coords.min(axis=0)
        size = max(extent) + padding
        return np.eye(3) * size
    
    def _parse_map_string(self, map_str):
        """Parse a map string like 'C:0.8,O:-0.4' to dict."""
        if not map_str:
            return {}
        result = {}
        for pair in map_str.split(','):
            if ':' in pair:
                key, val = pair.split(':')
                try:
                    result[key.strip()] = float(val.strip())
                except ValueError:
                    result[key.strip()] = val.strip()
        return result
    
    @staticmethod
    def _print_column_stats(column):
        """Print statistics for a DataFrame column."""
        print(f"  Column: {column.name}")
        print(f"  Max: {column.max():.4f}, Min: {column.min():.4f}")
        print(f"  Mean: {column.mean():.4f}, Std: {column.std():.4f}")


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Active Learning Pipeline for Force Field Development",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Input Files:
  The pipeline uses 5 separate input files for modular configuration:
  
  1. training.in  - Training/optimization parameters
  2. potential.in    - Force field model definitions (& sections)
  3. al.in - Sampling parameters and iteration settings
  4. scheduler.in    - HPC scheduler settings (SLURM/PBS)
  5. dft.in          - DFT software settings (QE/Gaussian)

Examples:
  # Using separate input files (recommended)
  python active_learning.py -m training.in -p potential.in -al al.in -sc scheduler.in -dft dft.in

  # Using legacy combined input file
  python active_learning.py -f combined.in

  # Generate template input files
  python active_learning.py --generate-templates
"""
    )
    
    # Input file arguments (modular mode)
    parser.add_argument('-m', '--methodology_file', type=str, default=None,
                        help='Methodology/training parameters file (training.in)')
    parser.add_argument('-p', '--potential_file', type=str, default=None,
                        help='Potential model definitions file (potential.in)')
    parser.add_argument('-al', '--al_config_file', type=str, default=None,
                        help='Active learning config file (al.in)')
    parser.add_argument('-sc', '--scheduler_file', type=str, default=None,
                        help='Scheduler config file (scheduler.in)')
    parser.add_argument('-dft', '--dft_file', type=str, default=None,
                        help='DFT settings file (dft.in)')
    
    # Path arguments
    parser.add_argument('-dp', '--datapath', type=str, default='data_al',
                        help='Main path for data storage')
    parser.add_argument('-rp', '--results_path', type=str, default='Results_al',
                        help='Path for results storage')
    
    # Override arguments (override config file values)
    parser.add_argument('-n', '--n_iterations', type=int, default=None,
                        help='Override: Number of active learning iterations')
    parser.add_argument('-b', '--batch_size', type=int, default=None,
                        help='Override: Batch size for configuration selection')
    parser.add_argument('-start', '--start_iteration', type=int, default=0,
                        help='Starting iteration (for continuing runs)')
    
    # Utility arguments
    parser.add_argument('--generate-templates', action='store_true',
                        help='Generate template input files and exit')
    
    return parser.parse_args()


def generate_template_files(output_dir='.'):
    """Generate template input files for all configurations."""
    os.makedirs(output_dir, exist_ok=True)
    
    # Active Learning config
    al_config = ActiveLearningConfig()
    al_config.to_file(os.path.join(output_dir, 'al.in'))
    
    # Scheduler config
    scheduler_config = SchedulerConfig()
    scheduler_config.to_file(os.path.join(output_dir, 'scheduler.in'))
    
    # DFT config
    dft_config = DFTConfig()
    dft_config.to_file(os.path.join(output_dir, 'dft.in'))
    
    # Methodology template
    methodology_template = """# Methodology/Training Parameters
# Generated template - modify as needed

representation  = AA
storing_path    = Results_al
run             = 0
runpath_attributes : run

max_ener        = 1.0
force_importance = 1.0
rclean          = 6.0
max_force       = 0.003
clean_perc      = 0.8
bC              = 50.0
bS              = 20.0

optimization_method = Adam
opt_disp        = 0
optimize        = 1
costf           = MSEo

training_method = fixed_lambda
random_initializations = 4
npareto         = 6
lambda_force    = 0.1

normalize_data  = 1

regularization_method = lasso
reg_par         = 0.00001

maxiter         = 130
max_moves       = 100
increased_stochasticity = 0.2
SLSQP_batchsize = 100000
tolerance       = 0.000001

train_perc      = 0.8
sampling_method = random
seed            = 1291412

polish          = 0
popsize         = 90
mutation        : 0.5 1.0
recombination   = 0.7

initial_temp    = 5230.0
restart_temp_ratio = 0.00002
local_search_scale = 1.0
accept          = -5.0
visit           = 2.62

learning_rate   = 0.0055
beta1           = 0.9
beta2           = 0.999
epsilon_adam    = 0.00000001
batch_size      = 50
decay_rate      = 0.015
weighting_method = Boltzman
w               = 1.0
bT              = 5.0

nLD             = 1
nPW             = 2
nBO             = 2
nAN             = 2
nDI             = 2

rho_r0          = 0.1
rho_rc          = 5.5

distance_map    = {('C', 'H'): (0.0, 1.2), ('N', 'H'): (0, 1.2)}
reference_energy = {'value': 0.0}
struct_types    = [('Ag',), ('C', 'H', 'N')]
rigid_types     = []
perturbation_method = atoms
lammps_potential_extra_lines = ['']
rigid_style     = single
extra_pair_coeff = {}
not_optimize_force_for = []
"""
    with open(os.path.join(output_dir, 'training.in'), 'w') as f:
        f.write(methodology_template)
    
    # Potential template
    potential_template = """# Potential Model Definitions
# Generated template - modify as needed
# Each model starts with &NAME and ends with /

&PW0 Ag C
FUNC LJ
sigma      : 3.0000000000000  1  0.20000  4.00000    0.00000
epsilon    : 0.5000000000000  1  0.00010  450.00000  0.00000
/

&PW0 Ag H
FUNC LJ
sigma      : 2.5000000000000  1  0.00100  4.00000    0.00000
epsilon    : 0.2000000000000  1  0.00000  450.00000  0.00000
/

&BO0 C H
FUNC MorseBond
re         : 1.1000000000000  1  1.00000  4.00000    0.00000
De         : 1.0000000000000  1  0.00000  450.00000  0.00000
alpha      : 2.0000000000000  1  0.00010  7.00000    0.00000
/

"""
    with open(os.path.join(output_dir, 'potential.in'), 'w') as f:
        f.write(potential_template)
    
    print(f"Generated template files in '{output_dir}':")
    print("  - training.in")
    print("  - potential.in")
    print("  - al.in")
    print("  - scheduler.in")
    print("  - dft.in")


def main():
    """Main entry point."""
    args = parse_arguments()
    
    # Handle template generation
    if args.generate_templates:
        generate_template_files('.')
        return
    
    # Determine mode: modular or legacy
    if args.methodology_file and args.potential_file:
        # Modular mode
        methodology_file = args.methodology_file
        potential_file = args.potential_file
    else:
        print("Error: Must provide: ")
        print("  - Both -m (training.in) and -p (potential.in) for modular mode")
        print("\nUse --generate-templates to create template input files.")
        return
    
    # Load configuration files
    al_config = ActiveLearningConfig()
    if args.al_config_file:
        al_config = ActiveLearningConfig.from_file(args.al_config_file)
    
    scheduler_config = SchedulerConfig()
    if args.scheduler_file:
        scheduler_config = SchedulerConfig.from_file(args.scheduler_file)
    
    dft_config = DFTConfig()
    if args.dft_file:
        dft_config = DFTConfig.from_file(args.dft_file)
    
    # Apply command-line overrides
    if args.n_iterations is not None:
        al_config.n_iterations = args.n_iterations
    if args.batch_size is not None:
        al_config.batch_size = args.batch_size
    
    # Create and run pipeline
    pipeline = ActiveLearningPipeline(
        methodology_file=methodology_file,
        potential_file=potential_file,
        al_config=al_config,
        scheduler_config=scheduler_config,
        dft_config=dft_config,
        datapath=args.datapath,
        results_path=args.results_path
    )
    pipeline.run(start_iteration=args.start_iteration)


if __name__ == '__main__':
    main()
