#!/usr/bin/env python3
"""
Generate a template potential.in file from training.in and L0 configs.

This script:
1. Reads training.in to get distance_map and other settings
2. Reads all configs from data_al/L0/
3. Detects all interaction types (bonds, angles, dihedrals, special_types)
4. Creates a template potential.in with:
   - MorseBond for bonds
   - LJ for pair-wise (PW)
   - harmonic for angles
   - Fourier for dihedrals
   All with 1.0 regularization and physically realistic bounds.
"""

import os
import sys
import numpy as np
import pandas as pd
from collections import defaultdict

# Add repository to path
repo_path = os.path.dirname(os.path.abspath(__file__))
if repo_path not in sys.path:
    sys.path.insert(0, repo_path)

from FF_Develop import (
    Setup_Interfacial_Optimization, 
    Data_Manager, 
    Interactions,
    al_help
)


def read_training_in(filepath='training.in'):
    """Parse training.in file to extract key settings."""
    settings = {}
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                key, val = line.split('=', 1)
                key = key.strip()
                val = val.strip()
                settings[key] = val
    return settings


def parse_distance_map(distance_map_str):
    """Parse distance_map string from training.in into a dictionary."""
    # e.g., "{ ('C', 'H'): (0.0, 1.2), ('N','H'):(0,1.2) }"
    try:
        return eval(distance_map_str)
    except:
        return {}


def read_all_xyz_from_dir(directory):
    """Read all .xyz files from a directory into a single DataFrame."""
    all_data = []
    
    if not os.path.exists(directory):
        print(f"Warning: Directory {directory} does not exist")
        return pd.DataFrame()
    
    for fname in os.listdir(directory):
        if fname.endswith('.xyz'):
            fpath = os.path.join(directory, fname)
            try:
                df = Data_Manager.read_xyz(fpath)
                df['sys_name'] = fname.replace('.xyz', '')
                all_data.append(df)
            except Exception as e:
                print(f"Warning: Could not read {fpath}: {e}")
    
    if not all_data:
        print(f"Warning: No .xyz files found in {directory}")
        return pd.DataFrame()
    
    return pd.concat(all_data, ignore_index=True)


def estimate_bond_params(bond_distances):
    """Estimate MorseBond parameters from observed distances."""
    if len(bond_distances) == 0:
        return {'D': 100.0, 'alpha': 2.0, 'r0': 1.5}
    
    r0 = np.mean(bond_distances)
    r_std = np.std(bond_distances) if len(bond_distances) > 1 else 0.05
    
    # Morse: U = D * (1 - exp(-alpha*(r-r0)))^2
    # D ~ bond dissociation energy (kcal/mol), typically 80-150 for organic
    # alpha ~ 2.0 for typical bonds
    D = 100.0
    alpha = 2.0 if r_std < 0.01 else 1.5 / max(r_std, 0.01)
    alpha = np.clip(alpha, 1.0, 3.0)
    
    return {'D': D, 'alpha': alpha, 'r0': r0}


def estimate_angle_params(angle_values):
    """Estimate harmonic angle parameters from observed angles."""
    if len(angle_values) == 0:
        return {'th0': 1.91, 'k': 50.0}  # ~109.5 degrees
    
    th0 = np.mean(angle_values)
    # k ~ force constant, typically 30-100 kcal/mol/rad^2
    k = 50.0
    
    return {'th0': th0, 'k': k}


def estimate_lj_params(pair_type):
    """Estimate LJ parameters based on atom types."""
    # sigma ~ sum of vdW radii, epsilon ~ interaction strength
    vdw_radii = {
        'H': 1.2, 'C': 1.7, 'N': 1.55, 'O': 1.52, 'S': 1.8,
        'F': 1.47, 'Cl': 1.75, 'Br': 1.85, 'I': 1.98,
        'Ag': 1.72, 'Au': 1.66, 'Cu': 1.4, 'Pt': 1.75,
        'Fe': 1.4, 'Zn': 1.39, 'P': 1.8
    }
    
    # Extract base types if special types (contain '--')
    types = []
    for t in pair_type:
        base = t.split('--')[0] if '--' in t else t
        types.append(base)
    
    r1 = vdw_radii.get(types[0], 1.7)
    r2 = vdw_radii.get(types[1], 1.7)
    
    sigma = (r1 + r2) / 2.0 * 1.12  # ~2^(1/6) factor
    epsilon = 0.1  # kcal/mol, conservative default
    
    return {'sigma': sigma, 'epsilon': epsilon}


def write_potential_in(output_path, bond_types, angle_types, dihedral_types, pw_types,
                       bond_stats, angle_stats):
    """Write potential.in file with detected interaction types."""
    
    with open(output_path, 'w') as f:
        f.write('# Potential Model Definitions\n')
        f.write('# Generated by generate_potential_template.py\n')
        f.write('# Using special types detected from data_al/L0/ configs\n\n')
        
        # ========== BONDS (MorseBond) ==========
        f.write('# ========== BONDS (MorseBond) ==========\n\n')
        for btype in sorted(bond_types):
            type_str = ' '.join(btype)
            params = estimate_bond_params(bond_stats.get(btype, []))
            
            f.write(f'&BO0 {type_str}\n')
            f.write('FUNC MorseBond\n')
            # D: dissociation energy
            f.write(f'D          : {params["D"]:.7f}  1  10.00000  200.00000    1.00000 \n')
            # alpha: width parameter
            f.write(f'alpha      : {params["alpha"]:.7f}  1  0.50000  4.00000    1.00000 \n')
            # r0: equilibrium distance
            r0_low = max(0.8, params["r0"] - 0.2)
            r0_high = params["r0"] + 0.2
            f.write(f'r0         : {params["r0"]:.7f}  1  {r0_low:.5f}  {r0_high:.5f}    1.00000 \n')
            f.write('/\n\n')
        
        # ========== ANGLES (harmonic) ==========
        f.write('# ========== ANGLES (harmonic) ==========\n\n')
        for atype in sorted(angle_types):
            type_str = ' '.join(atype)
            params = estimate_angle_params(angle_stats.get(atype, []))
            
            f.write(f'&AN0 {type_str}\n')
            f.write('FUNC harmonic\n')
            # th0: equilibrium angle (radians)
            th0_low = max(0.5, params["th0"] - 0.3)
            th0_high = min(3.14, params["th0"] + 0.3)
            f.write(f'th0        : {params["th0"]:.7f}  1  {th0_low:.5f}  {th0_high:.5f}    1.00000 \n')
            # k: force constant
            f.write(f'k          : {params["k"]:.7f}  1  5.00000  150.00000    1.00000 \n')
            f.write('/\n\n')
        
        # ========== PAIR-WISE / LJ ==========
        f.write('# ========== PAIR-WISE / LJ ==========\n\n')
        for pwtype in sorted(pw_types):
            type_str = ' '.join(pwtype)
            params = estimate_lj_params(pwtype)
            
            f.write(f'&PW0 {type_str}\n')
            f.write('FUNC LJ\n')
            # sigma: distance parameter
            f.write(f'sigma      : {params["sigma"]:.7f}  1  1.50000  4.50000    1.00000 \n')
            # epsilon: energy parameter
            f.write(f'epsilon    : {params["epsilon"]:.7f}  1  0.00100  5.00000    1.00000 \n')
            f.write('/\n\n')
        
        # ========== DIHEDRALS (Fourier) ==========
        f.write('# ========== DIHEDRALS (Fourier) ==========\n\n')
        for dtype in sorted(dihedral_types):
            type_str = ' '.join(dtype)
            
            f.write(f'&DI0 {type_str}\n')
            f.write('FUNC Fourier\n')
            # Fourier coefficients k1-k6, start near zero
            for i in range(1, 7):
                f.write(f'k{i}         : 0.0000000  1  -15.00000  15.00000    1.00000 \n')
            f.write('/\n\n')
    
    print(f"Written potential.in to {output_path}")


def main():
    # ========== 1. Read training.in ==========
    training_in_path = 'training.in'
    if not os.path.exists(training_in_path):
        print(f"Error: {training_in_path} not found")
        sys.exit(1)
    
    print(f"Reading {training_in_path}...")
    settings = read_training_in(training_in_path)
    
    # Parse distance_map
    distance_map_str = settings.get('distance_map', '{}')
    distance_map = parse_distance_map(distance_map_str)
    print(f"Distance map: {distance_map}")
    
    # Get other relevant settings
    rho_r0 = float(settings.get('rho_r0', 0.1))
    rho_rc = float(settings.get('rho_rc', 5.0))
    representation = settings.get('representation', 'AA').strip()
    
    # ========== 2. Read configs from data_al/L0/ ==========
    l0_dir = 'data_al/L0'
    print(f"\nReading configs from {l0_dir}...")
    data = read_all_xyz_from_dir(l0_dir)
    
    if len(data) == 0:
        print(f"Error: No data loaded from {l0_dir}")
        sys.exit(1)
    
    print(f"Loaded {len(data)} configurations")
    
    # ========== 3. Create minimal setup for Interactions ==========
    # Create a minimal setup object
    class MinimalSetup:
        def __init__(self):
            self.representation = representation
            self.rho_r0 = rho_r0
            self.rho_rc = rho_rc
            self.distance_map = distance_map
            self.runpath = '.'
    
    setup = MinimalSetup()
    
    # ========== 4. Setup bonds and make interactions ==========
    print("\nSetting up bonds...")
    manager = Data_Manager(data, setup)
    manager.setup_bonds(distance_map)
    
    print("Computing interactions...")
    intersHandler = Interactions(
        data, setup,
        atom_model=representation,
        find_vdw_connected=True,
        find_vdw_unconnected=True,
        find_angles=True,
        find_dihedrals=True,
        find_densities=False,  # Skip densities for template generation
        vdw_bond_dist=3,
        rho_r0=rho_r0,
        rho_rc=rho_rc
    )
    
    # ========== 5. Collect all special types ==========
    print("\nDetecting special types...")
    
    special_bond_types = set()
    special_angle_types = set()
    special_dihedral_types = set()
    special_pw_types = set()
    
    # Statistics for parameter estimation
    bond_distances = defaultdict(list)
    angle_values = defaultdict(list)
    
    for idx, row in data.iterrows():
        at_types = row['at_type']
        coords = np.array(row['coords'])
        
        try:
            inters = row['interactions']
        except:
            # Compute interactions for this row
            Bonds = row.get('Bonds', np.array([]))
            if len(Bonds) == 0:
                continue
            
            neibs = Interactions.get_neibs(
                Interactions.get_connectivity(Bonds, at_types, []),
                len(at_types)
            )
            special_types = Interactions.get_special_types(at_types, neibs)
            
            connectivity = Interactions.get_connectivity(Bonds, at_types, [])
            angles = Interactions.get_angles(connectivity, neibs, at_types)
            dihedrals = Interactions.get_dihedrals(angles, neibs, at_types)
            
            # Re-label with special types
            for pair_ids in connectivity.keys():
                _, special_label = Interactions.sorted_id_and_type(special_types, pair_ids)
                special_bond_types.add(special_label)
                
                # Compute distance for stats
                i, j = pair_ids
                dist = np.linalg.norm(coords[i] - coords[j])
                bond_distances[special_label].append(dist)
            
            for triple_ids in angles.keys():
                _, special_label = Interactions.sorted_id_and_type(special_types, triple_ids)
                special_angle_types.add(special_label)
                
                # Compute angle for stats
                i, j, k = triple_ids
                v1 = coords[i] - coords[j]
                v2 = coords[k] - coords[j]
                cos_ang = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-10)
                ang = np.arccos(np.clip(cos_ang, -1, 1))
                angle_values[special_label].append(ang)
            
            for quad_ids in dihedrals.keys():
                _, special_label = Interactions.sorted_id_and_type(special_types, quad_ids)
                special_dihedral_types.add(special_label)
    
    # For PW, use special types for non-bonded pairs
    # Collect unique special types from all configs
    all_special_types = set()
    for idx, row in data.iterrows():
        at_types = row['at_type']
        Bonds = row.get('Bonds', np.array([]))
        if len(Bonds) == 0:
            # No bonds, just use atom types
            for t in np.unique(at_types):
                all_special_types.add(f"{t}--")
        else:
            neibs = Interactions.get_neibs(
                Interactions.get_connectivity(Bonds, at_types, []),
                len(at_types)
            )
            special_types = Interactions.get_special_types(at_types, neibs)
            all_special_types.update(special_types)
    
    # Generate PW pairs from unique special types
    special_list = sorted(all_special_types)
    for i, t1 in enumerate(special_list):
        for t2 in special_list[i:]:
            if t1 <= t2:
                special_pw_types.add((t1, t2))
            else:
                special_pw_types.add((t2, t1))
    
    # ========== 6. Print summary ==========
    print(f"\n{'='*50}")
    print("DETECTED SPECIAL TYPES SUMMARY")
    print(f"{'='*50}")
    print(f"\nBonds ({len(special_bond_types)} types):")
    for bt in sorted(special_bond_types):
        print(f"  {bt}")
    
    print(f"\nAngles ({len(special_angle_types)} types):")
    for at in sorted(special_angle_types):
        print(f"  {at}")
    
    print(f"\nDihedrals ({len(special_dihedral_types)} types):")
    for dt in sorted(special_dihedral_types):
        print(f"  {dt}")
    
    print(f"\nPair-wise ({len(special_pw_types)} types):")
    for pt in sorted(special_pw_types):
        print(f"  {pt}")
    
    # ========== 7. Write potential.in ==========
    output_path = 'potential.in'
    write_potential_in(
        output_path,
        special_bond_types,
        special_angle_types,
        special_dihedral_types,
        special_pw_types,
        bond_distances,
        angle_values
    )
    
    print(f"\n{'='*50}")
    print(f"Template potential.in written to {output_path}")
    print(f"{'='*50}")
    print("\nFunction types used:")
    print("  - Bonds: MorseBond (D, alpha, r0)")
    print("  - Angles: harmonic (th0, k)")
    print("  - Dihedrals: Fourier (k1-k6)")
    print("  - Pair-wise: LJ (sigma, epsilon)")
    print("\nAll parameters have regularization = 1.0")


if __name__ == '__main__':
    main()
